/**
 * Board-server wire view models for the BoardAdapter (ADR 0011 §6).
 *
 * Entity types that the board OpenAPI names (TaskOut, BoardOut, TaskInboxOut,
 * TaskInboxItem) are re-exported from the generated board OpenAPI types
 * (src/types/board-openapi.d.ts, regenerated by `npm run codegen:board`) —
 * the generated file is the single source of truth. Only shapes the board
 * serves as anonymous `dict[str, Any]` (health, memory item envelope, the
 * mnemos-search proxy) stay hand-written here, mirroring the convention of
 * gateway/types.ts for the mnemos side.
 */
import type { components } from "@/types/board-openapi";

type Schemas = components["schemas"];

// --- Generated entity types (components["schemas"]) -------------------------

/** Board projection — board `BoardOut` schema (`GET /api/board`). */
export type BoardSummary = Schemas["BoardOut"];

/** Board task row — board `TaskOut` schema (SSE `task.*` payloads, board). */
export type BoardTask = Schemas["TaskOut"];

/** AGG-1 inbox payload — board `TaskInboxOut` schema (`GET /api/tasks/inbox`). */
export type TaskInbox = Schemas["TaskInboxOut"];

/** One inbox row — board `TaskInboxItem` schema. */
export type TaskInboxEntry = Schemas["TaskInboxItem"];

/**
 * Merged memory page — board `MemoryListOut` schema (`GET /api/memories`).
 * Cursor contract of ADR 0011 §11; `errors` carries per-store degradation.
 */
export type MergedMemoriesPage = Schemas["MemoryListOut"];

/**
 * One merged-list row — board `MemoryListItem` schema. SEC-4: only an
 * excerpt travels in the list (never full content); `server` disambiguates
 * per-store id collisions.
 */
export type MergedMemoryListItem = Schemas["MemoryListItem"];

/** Aggregated tag listing — board `TagListOut` schema (`GET /api/tags`). */
export type MergedTags = Schemas["TagListOut"];

// --- Tag drill (UI-17, spec 2026-09-21-tags-cloud-spec §5; wire types are
// hand-written because the board serves the drill as an anonymous
// `dict[str, Any]` — same convention as BoardHealth/MemoryPulse above). ------

/** Drill query params (`GET /api/tags/{tag}/drill?limit=`, server cap 25). */
export interface TagDrillParams {
  /** Max memories returned per the merged answer (server clamps to 25). */
  readonly limit?: number;
}

/** One board task carrying the drilled tag (server projection of TaskOut). */
export interface TagDrillTask {
  readonly id: string;
  readonly title: string;
  readonly col: string;
  readonly agents: readonly string[];
  readonly env: string;
}

/**
 * One memory matching the drilled tag — excerpt-only row (SEC-4 mirror of
 * the server drill projection; `server` is the contributing store, absent
 * on single-store mnemos gateways).
 */
export interface TagDrillMemory {
  readonly id: string;
  readonly title: string;
  readonly tags: readonly string[];
  readonly server?: string | null;
  readonly created_at?: string | null;
  readonly status?: string | null;
  readonly excerpt: string;
}

/** One unreachable store in a drill answer (mirrors the wire error rows). */
export interface TagDrillStoreError {
  readonly server?: string;
  readonly status?: number;
}

/**
 * `GET /api/tags/{tag}/drill` — everything tied to one tag (UI-17 §5).
 * BE-13 (viewer closed): memories here still ride the search ranker (a
 * SUBSET — keep the wire type honest), but the drill VIEW no longer renders
 * them — it lists through `listMemories({ tags })` instead. The header
 * count stays sourced from the full `/api/tags` aggregate.
 */
export interface TagDrill {
  readonly ok: boolean;
  readonly tag: string;
  readonly tasks: readonly TagDrillTask[];
  readonly memories: readonly TagDrillMemory[];
  readonly errors: readonly TagDrillStoreError[];
}

// --- Ф2 task-domain wire types (generated entity schemas) ---------------------

/** One agent report — board `ReportOut` schema. */
export type TaskReport = Schemas["ReportOut"];

/** Report history — board `ReportsOut` schema (`GET /api/tasks/{id}/reports`). */
export type TaskReports = Schemas["ReportsOut"];

/** One audit event row — board `EventItem` schema (ts + title + detail?). */
export type TaskHistoryEvent = Schemas["EventItem"];

/** One linked-memory row — board `MemoryItem` schema (ts?/source?/detail?). */
export type TaskHistoryMemory = Schemas["MemoryItem"];

/** Merged task timeline — board `HistoryOut` schema (`GET /api/tasks/{id}/history`). */
export type TaskHistory = Schemas["HistoryOut"];

/**
 * Resolved task memory links — board `TaskMemoriesOut` schema
 * (`GET /api/tasks/{id}/memories`). `items` maps a memory id onto an
 * excerpt-only card (SEC-4); `sources` maps the id onto the resolving
 * server; `unresolved` lists links no active server could resolve.
 */
export type TaskMemories = Schemas["TaskMemoriesOut"];

/**
 * Archive page — board `ArchiveOut` schema (`GET /api/archive`). `items` is
 * the limit/offset page; `projects` groups the FULL matching set (stable
 * teaser counts under pagination, BE-11b); `count` is the legacy total key.
 */
export type ArchivePage = Schemas["ArchiveOut"];

/** Archive query params (mirrors the server's filter contract). */
export interface ArchiveParams {
  /** LIKE over title/summary. */
  readonly q?: string;
  /** Exact workflow-status match (`TASK_STATUSES`; empty = all). */
  readonly status?: string;
  /** Exact column match (`VALID_STATUSES`; empty = all). */
  readonly col?: string;
  /** Member-of-agents-array match. */
  readonly agent?: string;
  /** Exact project match. */
  readonly project?: string;
  /** Page size (server clamps to 0..200; default 50). */
  readonly limit?: number;
  /** Page offset (≥ 0). */
  readonly offset?: number;
}

// --- Ф3 mutation wire types (generated entity schemas) -------------------------

/** Create payload — board `TaskCreate` schema (`POST /api/tasks`). */
export type TaskCreateInput = Schemas["TaskCreate"];

/**
 * Content patch — board `TaskPatch` schema (`PATCH /api/tasks/{id}`).
 * `force: true` overrides the BE-12 24h lock (the server echoes forced
 * edits back with `forced: true`); `status` is workflow, never content —
 * the 423 window does not apply to it.
 */
export type TaskPatchInput = Schemas["TaskPatch"];

/** Move payload — board `MoveBody` schema (`POST /api/tasks/{id}/move`). */
export type TaskMoveInput = Schemas["MoveBody"];

/** Archive ack — board `OkOut` schema (`POST /api/tasks/{id}/archive`). */
export type TaskMutationAck = Schemas["OkOut"];

/** Unarchive result — board `UnarchiveOut` schema; `task` may be null. */
export type TaskUnarchiveResult = Schemas["UnarchiveOut"];

/**
 * Inbox scan counters — board `TaskInboxRefreshOut` schema
 * (`POST /api/tasks/inbox/refresh`): `found` rows seen, `new` rows stored.
 */
export type InboxRefreshResult = Schemas["TaskInboxRefreshOut"];

/**
 * Pre-adoption edit payload — board `TaskInboxEditSpec` schema
 * (`PATCH /api/tasks/inbox/{memory_id}`, UI-25). Partial: omitted fields
 * stay at their current mirror/edited value; the server stores the overlay
 * and adopt merges it over the mirror fields.
 */
export type InboxEditInput = Schemas["TaskInboxEditSpec"];

// --- AGW-1 agents-domain wire types (ARCH-9, ADR 0009 Amd 2; SCHED-1) ----------
// Hand-written refinements over the generated schemas where the server
// answers anonymous dicts (routing, executor-list meta) or enum-ish strings;
// entities the OpenAPI already names precisely are re-exported verbatim.
// The full REST projection NEVER carries `claim_token` (secret — it exists
// only inside the claim/finish machine calls) or `spec_snapshot` (immutable
// execution view — only its `spec_hash` fingerprint travels).

/** Assignment lifecycle — the frozen 7-state dictionary (ADR 0009 §4). */
export type AssignmentLifecycleState =
  "queued" | "claimed" | "running" | "done" | "failed" | "cancelled" | "expired";

/**
 * Routing annotation `{resolved, reason}` — computed per GET over the
 * executor registry (Amd 2 §5: explicit pin → assignment specialist → task
 * specialists → project default → global default → auto best-match →
 * unmatched), stored nowhere. `resolved: null` + reason "unmatched" means
 * the assignment is visible to every poller.
 */
export interface RoutingAnnotation {
  /** Executor id the chain resolves to; null = no route (unmatched). */
  readonly resolved: string | null;
  /** Resolution tier: explicit | specialist | task-specialists | project-default | global-default | auto | unmatched. */
  readonly reason: string;
}

/**
 * One assignment row — board `AssignmentOut` with the anonymous `routing`
 * dict re-typed. `claimed_by` is the DECLARED identity of the claimer —
 * server-unverified, the UI renders it with the unverified affordance.
 */
export interface AssignmentItem {
  readonly id: number;
  readonly task_id: string;
  readonly specialist: string;
  readonly harness: string;
  readonly state: AssignmentLifecycleState;
  /** Who queued the attempt: owner | automation | … (audit actor). */
  readonly created_by: string;
  /** Declared identity of the claimer (unverified, may stay null). */
  readonly claimed_by?: string | null;
  readonly note: string;
  /** Fingerprint of the frozen spec snapshot (the snapshot itself stays server-side). */
  readonly spec_hash: string;
  /** Explicit executor pin — empty string means chain resolution. */
  readonly executor_id: string;
  /** Registry id of the executor that actually claimed (fact, not hint). */
  readonly claimed_by_executor: string;
  readonly created_at: string;
  readonly claimed_at?: string | null;
  readonly started_at?: string | null;
  readonly heartbeat_at?: string | null;
  readonly finished_at?: string | null;
  /** Denormalized project/domain tags (metadata tier). */
  readonly topics: readonly string[];
  readonly routing?: RoutingAnnotation | null;
}

/** Assignment queue page — board `AssignmentsOut` (items re-typed). */
export interface AssignmentsPage {
  readonly ok: boolean;
  readonly count: number;
  readonly items: readonly AssignmentItem[];
}

/** Assignment queue filters (`GET /api/assignments`). */
export interface AssignmentListParams {
  /** Exact lifecycle state (dictionary value; empty = all). */
  readonly state?: AssignmentLifecycleState;
  /** Exact task filter. */
  readonly task_id?: string;
  /**
   * Presence piggyback + routing hint, NOT a server-side list filter: an
   * authenticated executor polling with its own id ticks its last_seen
   * clock (ARCH-9). The UI filters by executor client-side.
   */
  readonly executor_id?: string;
}

/** Create payload — board `AssignmentCreate` (`POST /api/assignments`). */
export interface AssignmentCreateInput {
  readonly task_id: string;
  readonly specialist: string;
  /** Harness id (a value of the server harness dictionary, wave 3C; default "zcode"). */
  readonly harness: string;
  /** Explicit executor pin — omitted/empty means chain resolution. */
  readonly executor_id?: string;
}

/** Create result — board `AssignmentCreatedOut` (assignment re-typed). */
export interface AssignmentCreatedResult {
  readonly ok: boolean;
  readonly assignment: AssignmentItem;
}

/**
 * Cancel result — board `AssignmentFinishedOut` (assignment re-typed).
 * `moved` is `[from, to]` when the task column returned to open, empty
 * otherwise; `report` stays null on cancel (it belongs to done/fail).
 */
export interface AssignmentCancelledResult {
  readonly ok: boolean;
  readonly assignment: AssignmentItem;
  readonly task?: BoardTask | null;
  readonly moved: readonly string[];
  readonly report?: TaskReport | null;
}

/** Executor presence — computed from the last_seen TTL on read, never stored. */
export type ExecutorPresence = "online" | "stale" | "offline";

/** Registry ladder state (Amd 2 §4: machine bootstrap → owner decision). */
export type ExecutorRegistryState = "pending" | "approved" | "revoked";

/** Executor transport (mesh is dispatch-ineligible until R4 lands). */
export type ExecutorTransport = "local-poll" | "mesh-r4";

/**
 * One executor row — board `ExecutorOut` with the enum-ish strings narrowed
 * (presence/state/transport are closed server-side sets). The declared
 * identity (name/host/harness/version) is executor-claimed and
 * server-UNVERIFIED — the UI renders it as such (spec §2.2).
 */
export interface ExecutorItem {
  readonly id: string;
  readonly name: string;
  readonly harness: string;
  readonly host: string;
  readonly transport: ExecutorTransport;
  /** Owner-declared allowlist mappings (specialist roles this executor takes). */
  readonly capabilities: readonly string[];
  readonly version: string;
  /** Routing kill-switch (owner PATCH; disabled executors never resolve). */
  readonly enabled: boolean;
  readonly state: ExecutorRegistryState;
  readonly last_seen: string;
  readonly presence: ExecutorPresence;
  /**
   * UXE-2 (07a §4): the honest computed connection lifecycle. Computed ON
   * READ server-side, never persisted; the human labels live in i18n, the
   * state LIST in `meta.lifecycle.states` — clients read, never hardcode.
   * OPTIONAL: pre-UXE-2 boards omit it; the UI falls back to presence.
   */
  readonly status?: ExecutorLifecycleStatus;
  /** Registration leg: '' = machine bootstrap, `enrollment:<id>` = mne_ leg. */
  readonly registered_via: string;
  readonly registered_at: string;
  readonly updated_at: string;
}

/**
 * UXE-2 honest lifecycle (07a dictionary §4) — the board `LifecycleStatus`
 * shape verbatim. `last_report_age_s` is `""` when no report exists yet
 * (honest absence, never a fake 0) and an integer otherwise; `next_action`
 * is the owner-facing step the UI renders as the pill's second line.
 */
export interface ExecutorLifecycleStatus {
  readonly state: ExecutorLifecycleState;
  readonly since: string;
  readonly last_report_age_s: number | "";
  readonly reason: string;
  readonly next_action: string;
}

/** The server-owned state list — mirrored from `meta.lifecycle.states`. */
export type ExecutorLifecycleState =
  | "provisioning"
  | "awaiting-approval"
  | "awaiting-first-report"
  | "online"
  | "silent"
  | "offline"
  | "disabled"
  | "revoked";

/**
 * Enrollment token row — board `EnrollmentOut` with `state` narrowed to the
 * server's closed set (AGW-5 phase 2 UI). Carries NO token material: the
 * store keeps only the hash; the mne_ plaintext appears exactly once, in the
 * create response (`EnrollmentCreatedResult.token`).
 */
export type EnrollmentState = "created" | "used" | "expired" | "revoked";

export interface EnrollmentItem {
  readonly enrollment_id: string;
  readonly label: string;
  readonly harness_hint: string;
  readonly name_hint: string;
  readonly state: EnrollmentState;
  readonly created_at: string;
  /** Single TTL (server constant, 15 min); renewal = a new token. */
  readonly expires_at: string;
  readonly used_at: string;
  /** Presenting IP of the registration leg — the owner's origin cross-check. */
  readonly used_ip: string;
  /** Set when state = used: the pending executor this token minted. */
  readonly executor_id: string;
}

/**
 * Mint answer — board `EnrollmentCreatedOut`. The token rides HERE ONLY.
 * `ca_fingerprint` is the AGW-9 parallel slice (the board's CA fingerprint
 * for the `--expect-fp` bootstrap flag): OPTIONAL until that slice lands —
 * the mint screen renders the one-command WITHOUT the flag when absent.
 */
export interface EnrollmentCreatedResult {
  readonly ok: boolean;
  readonly enrollment: EnrollmentItem;
  readonly token: string;
  readonly ca_fingerprint?: string;
}

/** Revoke answer — board `EnrollmentRevokedOut` (the fresh row; NO token). */
export interface EnrollmentRevokeResult {
  readonly ok: boolean;
  readonly enrollment: EnrollmentItem;
}

/** Enrollment list — board `EnrollmentListOut` (live + terminal history). */
export interface EnrollmentsPage {
  readonly ok: boolean;
  readonly count: number;
  readonly items: readonly EnrollmentItem[];
}

/** Mint request — empty strings mean «not provided» (server defaults). */
export interface EnrollmentCreateInput {
  readonly label?: string;
  readonly harness_hint?: string;
  readonly name_hint?: string;
}

// --- SSH provisioner (wave 4 AGW-11; design 2026-09-23-connect-provisioning) -

/** How the board logs into the target over the install-time SSH channel. */
export type ProvisionAuthKind = "key" | "password" | "alias";

/** Job lifecycle — board `provision_jobs.state` CHECK set, verbatim. */
export type ProvisionJobState =
  | "queued"
  | "connecting"
  | "installing"
  | "watching"
  | "done"
  | "failed";

/**
 * One provision job row — the GET /api/executors/provision/{id} `job`
 * projection. Carries NO secret material (the ssh secret and the mne_
 * token are transit-only server-side, never in a column or a frame);
 * `steps` is the server's JSON array of step strings, `error_code` is the
 * typed failure code the UI maps through the hint table.
 */
export interface ProvisionJobRow {
  readonly id: string;
  readonly host: string;
  readonly port: number;
  readonly auth_kind: ProvisionAuthKind | string;
  /** Display fingerprint of the PUBLIC half of the key (never derived
   * from a password server-side — CWE-759 fix); '' for alias auth. */
  readonly key_fingerprint: string;
  /** The pinned/presented HOST key fingerprint (canonical SHA256:base64);
   * '' until strict mode seeded it or TOFU filled it at first connect. */
  readonly host_key_fingerprint: string;
  readonly harness_hint: string;
  readonly board_url_for_host: string;
  readonly enrollment_id: string;
  readonly state: ProvisionJobState;
  readonly error_code: string;
  readonly steps: string;
  readonly created_at: string;
  readonly updated_at: string;
}

/** The enrollment leg of a job status read (used → executor_id is the win). */
export interface ProvisionEnrollmentStatus {
  readonly state: EnrollmentState | "";
  readonly expires_at: string;
  readonly executor_id: string;
}

/** GET /api/executors/provision/{job_id} answer (ui-token). */
export interface ProvisionJobStatus {
  readonly ok: boolean;
  readonly job: ProvisionJobRow;
  readonly enrollment: ProvisionEnrollmentStatus;
}

/** POST /api/executors/provision answer — 202; the mne_ token NEVER rides. */
export interface ProvisionCreatedResult {
  readonly ok: boolean;
  readonly job_id: string;
  readonly enrollment_id: string;
  readonly state: ProvisionJobState;
}

/** SSH auth leg of the provision request (board `ProvisionAuth`). */
export interface ProvisionAuthInput {
  readonly kind: ProvisionAuthKind;
  /** Password or private-key material (key auth) — transit-only. */
  readonly secret?: string;
  readonly passphrase?: string;
}

/**
 * POST /api/executors/provision body (board `ProvisionBody`): anti-spray
 * and charset gates are server-owned; the UI mirrors the host charset for
 * immediate feedback, never as the enforcement boundary.
 */
export interface ProvisionCreateInput {
  readonly name?: string;
  readonly host: string;
  readonly port?: number;
  readonly auth: ProvisionAuthInput;
  readonly harness_hint?: string;
  readonly board_url_for_host?: string;
  readonly expected_host_key_fingerprint?: string;
  readonly reuse_enrollment_id?: string;
}

/**
 * Registry page meta — the server-owned presence contract (spec §5.1): the
 * TTL constants (online ≤ 2 min, stale ≤ 10 min) and the sweeper cadence
 * travel WITH the data; clients read them, never hardcode.
 */
/**
 * Registry page meta — the server-owned presence contract (spec §5.1): the
 * TTL constants (online ≤ 2 min, stale ≤ 10 min) and the sweeper cadence
 * travel WITH the data; clients read them, never hardcode. UXE-2 adds the
 * lifecycle contract: the closed state list + the silent threshold (the
 * «ждёт первый доклад» → «молчит» corridor), same read-don't-hardcode rule.
 */
export interface ExecutorListMeta {
  readonly presence: {
    readonly online_max_age_s: number;
    readonly stale_max_age_s: number;
  };
  readonly sweeper_interval_s: number;
  /** UXE-2 (07a §4): server-owned lifecycle states + thresholds. */
  readonly lifecycle?: {
    readonly silent_max_age_s: number;
    readonly states: readonly ExecutorLifecycleStatus["state"][];
  };
}

/** Executor registry page — board `ExecutorListOut` (meta re-typed). */
export interface ExecutorsPage {
  readonly ok: boolean;
  readonly count: number;
  readonly items: readonly ExecutorItem[];
  readonly meta: ExecutorListMeta;
}

/**
 * Owner PATCH of one executor (`PATCH /api/executors/{id}`, ui-token; AGW-4
 * wave 2). Narrowed from the board `ExecutorPatch` schema: `state` accepts
 * only the two patchable targets (pending is NOT patchable — the ladder is
 * machine bootstrap → owner decision), omitted fields stay untouched.
 */
export interface ExecutorPatchInput {
  readonly name?: string;
  readonly state?: Exclude<ExecutorRegistryState, "pending">;
  readonly capabilities?: readonly string[];
  readonly enabled?: boolean;
}

/** PATCH answer — board `ExecutorStateChangeOut` (the fresh row echoes back). */
export interface ExecutorStateChangeResult {
  readonly ok: boolean;
  readonly executor: ExecutorItem;
}

/**
 * Harness dictionary row (wave 3C, design 2026-09-22 §C) — board
 * `HarnessOut`. The dictionary is the owner-managed nomination registry
 * that replaced the former closed-set UI mirror; `added_via` separates
 * seed rows from owner-added ones.
 */
export interface HarnessItem {
  readonly name: string;
  readonly added_at: string;
  readonly added_via: string;
  readonly note: string;
}

/** Harness dictionary page — board `HarnessListOut`. `seed_min_count` is
 * the guaranteed seed size; the UI never hardcodes the set. */
export interface HarnessesPage {
  readonly ok: boolean;
  readonly count: number;
  readonly items: readonly HarnessItem[];
  readonly meta: { readonly seed_min_count: number };
}

/** Add request — board `HarnessCreateBody` (name server-sanitized too). */
export interface HarnessCreateInput {
  readonly name: string;
  readonly note?: string;
}

/** Add answer — board `HarnessStateOut` (the fresh row echoes back). */
export interface HarnessStateResult {
  readonly ok: boolean;
  readonly harness: HarnessItem;
}

/** Execution settings read — board `ExecutionSettingsOut`. */
export type ExecutionSettings = Schemas["ExecutionSettingsOut"];

/**
 * Execution settings write — board `ExecutionSettingsBody` with `scope`
 * optional ('' global by default; 'project:<slug>' reserves per-project
 * defaults, Amd 2 §5). The fallback is the UI's no-silent-substitution
 * preview value; it never joins the GET routing chain.
 */
export interface ExecutionSettingsInput {
  /** Executor id or '' to clear the slot (Amd 2 §5 gates apply server-side). */
  readonly default_executor: string;
  /** Executor id or '' to clear the slot (global scope only). */
  readonly fallback_executor: string;
  readonly scope?: string;
}

// --- SCHED-1 automation wire types (ADR 0013; consumed by a later wave) -------

/** One schedule rule — board `ScheduleOut` schema. */
export type ScheduleRule = Schemas["ScheduleOut"];

/** Schedule create payload — board `ScheduleCreate` schema. */
export type ScheduleCreateInput = Schemas["ScheduleCreate"];

/** Schedule patch payload — board `SchedulePatch` schema (null = absent). */
export type SchedulePatchInput = Schemas["SchedulePatch"];

/** Schedule listing — board `SchedulesOut` schema. */
export type SchedulesPage = Schemas["SchedulesOut"];

/** «Запустить сейчас» result — board `ScheduleRunOut` schema. */
export type ScheduleRunResult = Schemas["ScheduleRunOut"];

/** One hook rule — board `HookOut` schema. */
export type HookRule = Schemas["HookOut"];

/** One condition clause — board `ConditionItem` schema (strict, no free text). */
export type ConditionItem = Schemas["ConditionItem"];

/** Hook create payload — board `HookCreate` schema. */
export type HookCreateInput = Schemas["HookCreate"];

/** Hook patch payload — board `HookPatch` schema (null = absent). */
export type HookPatchInput = Schemas["HookPatch"];

/** Hook listing — board `HooksOut` schema. */
export type HooksPage = Schemas["HooksOut"];

/** Rule DELETE ack — board `RuleDeletedOut` (soft-disable retention note). */
export type RuleDeletedAck = Schemas["RuleDeletedOut"];

/** One launch journal row — board `LaunchOut` schema. */
export type LaunchRow = Schemas["LaunchOut"];

/** Launch journal page — board `LaunchesOut` schema (cursor contract, ADR 0011 §11). */
export type LaunchesPage = Schemas["LaunchesOut"];

/** Engine/caps/condition-meta projection — board `AutomationStatusOut` schema. */
export type AutomationStatus = Schemas["AutomationStatusOut"];

/** Kill-switch + daily cap projection — board `AutomationSettingsOut` schema. */
export type AutomationSettings = Schemas["AutomationSettingsOut"];

/**
 * Settings PUT payload — board `AutomationSettingsBody` schema (the wire
 * accepts partial bodies; the settings form sends BOTH fields — the server
 * ignores `None`s and audits only effective changes, store.py ADR 0013 §6).
 */
export type AutomationSettingsInput = Schemas["AutomationSettingsBody"];

/** Launch journal filters (`GET /api/automation/launches`). */
export interface LaunchesParams {
  readonly rule_id?: number;
  /** schedule | hook (422 on garbage server-side). */
  readonly kind?: string;
  /** launched | skipped | missed. */
  readonly decision?: string;
  /** Page size (server caps at 200; default 50). */
  readonly limit?: number;
  /** Opaque cursor from a previous page's next_cursor. */
  readonly cursor?: string;
}

// --- Anonymous wire shapes (board answers `dict[str, Any]`) ------------------

/**
 * `GET /api/health` payload (anonymous dict on the wire). `servers`/`groups`
 * carry live store state; the adapter projects the scalars onto the viewer's
 * string-map `HealthStatus` and drops the nested arrays.
 */
export interface BoardHealth {
  readonly ok?: boolean;
  readonly service?: string;
  readonly board_tasks?: number;
  readonly servers?: readonly unknown[];
  readonly groups?: readonly unknown[];
}

/**
 * `GET /api/health` — per-store detail (Ф1 Overview «карточки здоровья
 * хранилища»). Captured from the live wire (recorded-corpus rule, QA verdict
 * §5): every server row carries the health-dot contract of ui-contract §7 —
 * `ok` reflects the cheap liveness probe only, never search latency.
 */
export interface BoardHealthServer {
  readonly name: string;
  readonly group_name?: string;
  readonly enabled?: boolean;
  readonly state?: string;
  readonly description?: string | null;
  readonly ok?: boolean;
  readonly latency_ms?: number | null;
  readonly error?: string | null;
  readonly memories_total?: number | null;
}

/** Full board health view the Overview consumes (scalars + store rows). */
export interface BoardHealthDetail {
  readonly ok: boolean;
  readonly service: string;
  readonly board_tasks: number;
  /** Server version (archcom C5 source) — the Sidebar version label; absent
   * on gateways that do not expose it (mock/legacy boards). */
  readonly app_version?: string | null;
  readonly servers: readonly BoardHealthServer[];
}

/**
 * `GET /api/memories/pulse` — merged recency feed (Ф1 Pulse page).
 * Anonymous dict on the wire; shape captured live against the board server
 * (see also server/app.py `memory_pulse_all`). `store_stats` is present ONLY
 * when the merged feed is empty (the server then explains what the stores
 * hold); `per_server` is the honest degradation report — `ok: false` rows
 * carry `detail` and contribute no items.
 */
export interface MemoryPulseItem {
  readonly id: string;
  readonly title: string;
  readonly tags: readonly string[];
  readonly status: string;
  readonly created_at: string;
  /** Provenance: the store that contributed the row (server-assigned). */
  readonly server: string;
  /**
   * Server-cut content fragment for the inline preview (≤400 chars, cut at
   * a whitespace boundary); null when the memory has no body. Untrusted
   * author content — render through TextEngine, never raw interpolation.
   */
  readonly content?: string | null;
}

export interface MemoryPulseServerNote {
  readonly server: string;
  readonly ok: boolean;
  /** How many items this store contributed before the merge cut. */
  readonly items: number;
  /** Failure detail (mnemos error body) — null on the happy path. */
  readonly detail: unknown;
}

export interface MemoryPulse {
  readonly ok: boolean;
  readonly scope: string;
  readonly kind: string;
  readonly items: readonly MemoryPulseItem[];
  readonly per_server: readonly MemoryPulseServerNote[];
  readonly store_stats?: readonly unknown[];
}

/** Pulse query params (`?scope=&project=&limit=`, limit capped at 20 server-side). */
export interface PulseParams {
  /** `'all'` (default), a group name, or one server name; unknown → 404. */
  readonly scope?: string;
  /** Exact project filter (empty = all projects). */
  readonly project?: string;
  readonly limit?: number;
}

/**
 * `GET /api/memories/item/{memory_id}` envelope. `ok: true` carries the
 * reshaped memory card from the first resolving server; `ok: false` is the
 * "not found on any active server" answer.
 */
export type BoardMemoryEnvelope =
  | {
      readonly ok: true;
      readonly server: string;
      readonly memory: {
        readonly id?: string;
        readonly title?: string | null;
        readonly content?: string | null;
        readonly raw_content?: string | null;
        readonly tags?: readonly string[];
        readonly status?: string | null;
        readonly memory_type?: string | null;
        readonly source?: string | null;
        readonly source_url?: string | null;
        readonly project?: string;
        readonly agent?: string;
        readonly created_at?: string | null;
        readonly updated_at?: string | null;
      };
    }
  | {
      readonly ok: false;
      readonly error?: string;
    };

/**
 * `GET /api/mnemos/search` payload (proxied mnemos search). Each hit is an
 * anonymous mnemos search object plus the board-added `server` provenance
 * field; `errors` lists stores whose slice failed.
 */
export interface BoardSearchResponse {
  readonly ok?: boolean;
  readonly results?: readonly unknown[];
  readonly errors?: readonly {
    readonly server?: string;
    readonly status?: number;
    readonly detail?: string | null;
  }[];
}

// --- CV-7 QR pairing + device sessions (ADR 0012; generated board schemas) ----

/**
 * One device session — board `DeviceOut` (`GET /api/devices`). NO token
 * material ever rides it (hash-only storage server-side, ADR 0012 §5);
 * `state` mirrors the server's active | expired | revoked lifecycle.
 */
export type DeviceSession = Schemas["DeviceOut"];

/** Device list — board `DevicesOut` (`GET /api/devices`). */
export type DevicesPage = Schemas["DevicesOut"];

/** Revoke answer — board `DeviceRevokedOut` (the final row snapshot). */
export type DeviceRevokedResult = Schemas["DeviceRevokedOut"];

/** Grants answer — board `DeviceGrantsOut` (`PUT /api/devices/{id}/grants`,
 * ADR 0012 Amendment §A.7): the updated row with its live granule set. */
export type DeviceGrantsResult = Schemas["DeviceGrantsOut"];

/**
 * The granule dictionary (ADR 0012 Amendment §A.7) as the viewer mirrors
 * it — LABELS ONLY. The server owns validation (unknown names → 422);
 * this list drives the toggle rendering and the PUT payload order.
 */
export const DEVICE_GRANULES = [
  "tasks",
  "reports",
  "inbox",
  "notifications",
] as const;

/** One granule id (a `DEVICE_GRANULES` member). */
export type DeviceGranule = (typeof DEVICE_GRANULES)[number];

/** Create answer — board `PairingCreatedOut` (`POST /api/pairing`, 201).
 * The code appears HERE and NOWHERE else on the owner leg (§2.1). */
export type PairingCreatedResult = Schemas["PairingCreatedOut"];

/** Owner-side status — board `PairingStatusOut` (`GET /api/pairing/{id}`);
 * the trusted side's only source of the verify digits + scan metadata. */
export type PairingStatus = Schemas["PairingStatusOut"];

/** Device-leg awaiting answer — board `PairingExchangeAwaitingOut` (202). */
export type PairingExchangeAwaiting = Schemas["PairingExchangeAwaitingOut"];

/** Device-leg issued answer — board `PairingIssuedOut` (200, one-shot). The
 * mnd_ token rides HERE ONLY (§2.5); the /pair page shows it once. */
export type PairingIssuedResult = Schemas["PairingIssuedOut"];

/** Confirm/cancel answer — board `PairingConfirmOut`. `outcome` is
 * confirmed | denied | idempotent (confirm) or revoked | idempotent (cancel). */
export type PairingConfirmResult = Schemas["PairingConfirmOut"];

/** Device exchange body (`POST /api/pairing/exchange`, NO auth). */
export interface PairingExchangeInput {
  readonly code: string;
  readonly device_name?: string;
}

/** Effective pairing lifecycle (ADR 0012 §10.1), computed client-side:
 * the wire `state` narrowed + the TTL-passed → expired view rule. */
export type PairingLifecycle =
  "created" | "scanned" | "confirmed" | "issued" | "expired" | "revoked";

// --- UI-28 «Активность» (`GET /api/activity`, spec 2026-09-27 §3.2) -----------
//
// Contract-first (week-0 convention): the server slice (feat/activity-server)
// lands in parallel — these types PIN the agreed wire shape. Everything is
// additive-compatible with the spec's row: extra OPTIONAL fields only.

/** Event families (the v1 dictionary, spec §2.1): the filter csv alphabet. */
export type ActivityType = "task" | "assignment" | "report";

/** Exact v1 kinds — the audit-table kinds the feed understands. */
export type ActivityKind =
  | "task.created"
  | "task.moved"
  | "task.updated"
  | "task.archived"
  | "task.unarchived"
  | "assignment.created"
  | "assignment.claimed"
  | "assignment.started"
  | "assignment.done"
  | "assignment.failed"
  | "assignment.cancelled"
  | "assignment.expired"
  | "report";

export function isActivityType(value: string): value is ActivityType {
  return value === "task" || value === "assignment" || value === "report";
}

/** True for the exact-kind spellings the `type=` csv also accepts. */
export function isActivityKind(value: string): value is ActivityKind {
  return (
    value === "report" ||
    value.startsWith("task.") ||
    value.startsWith("assignment.")
  );
}

/** Family of one kind (spec §2.1 table; `report` is its own family). */
export function activityTypeOfKind(kind: string): ActivityType {
  if (kind === "report") return "report";
  if (kind.startsWith("assignment.")) return "assignment";
  return "task";
}

/** One feed row — spec §3.2 exactly; optionals ride along additively. */
export interface ActivityItem {
  /** Monotonic audit-table id (the `before_id` cursor values). */
  readonly id: string;
  /** Event time (ISO 8601). */
  readonly ts: string;
  readonly kind: ActivityKind;
  readonly task_id: string;
  /** Best-effort join with tasks; absent once the task is deleted. */
  readonly task_title?: string;
  /** Actor wire string (ADR 0012 Amd §A.5); stripped for anonymous legs. */
  readonly actor?: string;
  /** Executor id when the event rode an executor leg. */
  readonly executor_id?: string;
  /** Best-effort host of the executor AT READ TIME (spec §3.2). */
  readonly host?: string;
  /** ≤200-char fact detail (clip, e.g. column transition / report excerpt). */
  readonly detail?: string;
  /** Report flavour (additive proposal; absent = intermediate). */
  readonly report_kind?: "intermediate" | "final";
}

/** One cursor page — the agreed envelope `{ok, count, items, truncated,
 * has_more}`. `ok`/`count` are additive conveniences the client does not
 * branch on; `has_more=false` is the honest end of the journal. */
export interface ActivityPage {
  readonly ok?: boolean;
  readonly count?: number;
  readonly items: readonly ActivityItem[];
  readonly has_more: boolean;
  /** Present (true) when the server silently clamped `limit` (CV-6). */
  readonly truncated?: boolean;
}

/** List params — cursor + the four server-side filters (spec §3.2). */
export interface ActivityParams {
  /** Strictly-lower cursor (stable pages under live refill). */
  readonly before_id?: string;
  /** Page size; server default 50, hard cap 200 (silent clamp). */
  readonly limit?: number;
  /** csv of families and/or exact kinds (`task,report`). */
  readonly type?: string;
  readonly task_id?: string;
  /** Matches declared identity and `machine:<id>` actor legs. */
  readonly agent?: string;
  /** Best-effort host filter (resolved at read time). */
  readonly host?: string;
}

/** One histogram bucket — counts by family inside the hour starting `ts`. */
export interface ActivityBucket {
  readonly ts: string;
  readonly total: number;
  readonly by_type: { readonly task: number; readonly assignment: number; readonly report: number };
}

/** Bucket view (`?bucket=hour&hours=24`): sparse — only hours WITH events. */
export interface ActivityBuckets {
  readonly buckets: readonly ActivityBucket[];
}

export interface ActivityBucketParams {
  readonly bucket?: "hour";
  readonly hours?: number;
  /** The same four filters as the list view. */
  readonly type?: string;
  readonly task_id?: string;
  readonly agent?: string;
  readonly host?: string;
}
