/**
 * Domain types for the gateway layer.
 *
 * Entity and response shapes are re-exported from the generated OpenAPI types
 * (src/types/openapi.d.ts, regenerated by `npm run codegen` against a live
 * mnemos) — the generated file is the single source of truth. Only UI-facing
 * query-param mirrors and shapes mnemos does not name in its schema (search
 * hits and traces are anonymous objects in mnemos 4.1) stay hand-written.
 */
import type { components, operations } from "@/types/openapi";

type Schemas = components["schemas"];
type Ops = operations;

// --- Generated entity types (components["schemas"]) ------------------------

/** A stored memory ("scroll") — mnemos `Memory` schema. */
export type Memory = Schemas["Memory"];

/** Memory lifecycle — mnemos `MemoryStatus` enum. */
export type MemoryStatus = Schemas["MemoryStatus"];

/** Tag with usage count (mnemos `GET /tags`; client-side fallback per ADR 0003). */
export type TagSummary = Schemas["TagCount"];

/** A2A session record (mounted under `/v1` on mnemos) — mnemos `SessionRead` schema. */
export type A2ASession = Schemas["SessionRead"];

// --- Generated response bodies (operations) --------------------------------

/** `GET /memories` response body. */
export type MemoryListResponse =
  Ops["list_memories_memories_get"]["responses"][200]["content"]["application/json"];

/** `GET /tags` response body. */
export type TagList =
  Ops["list_tags_tags_get"]["responses"][200]["content"]["application/json"];

/** `POST /search` response body — anonymous hit objects on mnemos 4.1. */
export type SearchResponse =
  Ops["search_search_post"]["responses"][200]["content"]["application/json"];

/** Liveness payload from mnemos `/health`. */
export type HealthStatus =
  Ops["health_health_get"]["responses"][200]["content"]["application/json"];

/** Aggregate counters from mnemos `/metrics` (free-form JSON object). */
export type Metrics =
  Ops["metrics_metrics_get"]["responses"][200]["content"]["application/json"];

/** `GET /traces` response body — anonymous pipeline trace entries. */
export type TraceList =
  Ops["list_traces_traces_get"]["responses"][200]["content"]["application/json"];

// --- UI-facing query-param mirrors ------------------------------------------
// The server names these only as anonymous operation parameters; they stay
// gateway view models until the T4 adapters wire them to the wire format.

/** Unified search request (FTS + semantic via mnemos `/search`). */
export interface SearchParams {
  query: string;
  tags?: string[];
  project?: string;
  limit?: number;
  include_raw?: boolean;
}

/** A single ranked search hit (mnemos returns anonymous objects; fields pinned for UI use). */
export interface SearchResult {
  id: string;
  title: string;
  content: string;
  tags: string[];
  score: number;
  search_type: "fts" | "semantic" | "hybrid";
  /**
   * Provenance — which store the hit lives in (`it["server"]`, stamped by the
   * board's merged search over every active server; UX-overhaul §7.3 Ф2 the
   * palette shows «где лежит»). OPTIONAL: mock/direct-mnemos adapters serve a
   * single unnamed store and omit the field — the UI renders provenance only
   * when the wire named it (honest absence).
   */
  server?: string;
}

/** Memory list filters (mnemos list endpoint). */
export interface ListMemoriesParams {
  status?: string;
  project?: string;
  /** Comma-separated tag filter (native listing filter, UI-17 spec §5.6). */
  tags?: string;
  limit?: number;
  offset?: number;
}

/** Pipeline trace entry (mnemos returns anonymous objects; fields pinned for UI use). */
export interface Trace {
  id: string;
  task_label?: string | null;
  [key: string]: unknown;
}
