import { describe, expect, it } from "vitest";
import { bodyToText, findSnippet, loadSearchIndex, searchDocs } from "./docsSearch";

/**
 * Search-index banner gate (ME-019 review P2-1, ADR 0020 Ф2): provenance
 * banners are whole-line HTML comments written by sync_docs into imported
 * bodies. They never reach the DOM (the sanitizer drops comment nodes), so
 * the search INDEX must not carry them either — otherwise "GENERATED"/
 * "sync_docs" become body tokens and the banner surfaces in the dialog
 * snippet. The slice lives in bodyToText (the index/snippet builder).
 */

describe("bodyToText banner slicing (P2-1)", () => {
  it("strips a leading GENERATED banner (line 0, the classic synced shape)", () => {
    const body = [
      "<!-- GENERATED by sync_docs from mnemos@23f0fce — правки через sync-config.yaml overlay -->",
      "",
      "# Заголовок",
      "",
      "Тело страницы.",
    ].join("\n");
    const text = bodyToText(body);
    expect(text).not.toContain("GENERATED");
    expect(text).not.toContain("sync_docs");
    expect(text).toContain("Тело страницы.");
  });

  it("strips banners AFTER a curator preamble and multi-line banner blocks", () => {
    const body = [
      "> Куратор: прогон один.",
      "",
      "<!-- GENERATED by sync_docs",
      "       from mnemos@23f0fce — правки через sync-config.yaml overlay -->",
      "",
      "Описание после многострочного баннера.",
    ].join("\n");
    const text = bodyToText(body);
    expect(text).not.toContain("GENERATED");
    expect(text).toContain("Куратор: прогон один.");
    expect(text).toContain("Описание после многострочного баннера.");
  });

  it("keeps real content: markup, links, headings survive the comment strip", () => {
    const text = bodyToText(
      "Абзац с [ссылкой](/docs/x) и **жирным**.\n\n## Раздел\n",
    );
    expect(text).toContain("ссылкой");
    expect(text).toContain("жирным");
    expect(text).toContain("Раздел");
  });
});

describe("search index carries no banners (real corpus gate)", () => {
  it("no indexed body text matches GENERATED/sync_docs, and snippets stay clean", async () => {
    const index = await loadSearchIndex("ru");
    expect(index.entries.length, "sanity: the ru corpus is indexed").toBeGreaterThan(10);

    // No body token may prefix-match the banner tokens…
    expect(searchDocs(index, "GENERATED"), "query: GENERATED").toEqual([]);
    for (const entry of index.entries) {
      expect(
        entry.bodyText.includes("GENERATED"),
        `${entry.slug}: banner text in indexed body`,
      ).toBe(false);
      expect(
        entry.bodyText.includes("sync_docs"),
        `${entry.slug}: sync_docs marker in indexed body`,
      ).toBe(false);
    }
    // …and the snippet projector must never surface a banner from any body.
    const tokens = ["generated"];
    for (const entry of index.entries) {
      const snippet = findSnippet(entry.bodyText, tokens);
      expect(snippet.includes("GENERATED"), `${entry.slug}: banner in snippet`).toBe(
        false,
      );
    }
  });
});
