#!/usr/bin/env python3
"""API hub generator — /docs/api (owner directive 2026-09-29, board ME-038).

The api hub is the FOURTH docs hub and the first CROSS-CUTTING one: it
aggregates the API surfaces of the whole ecosystem under one URL prefix
(`api/…`). sync_docs.py cannot host it — one sync project is one repo — so
this generator owns the prefix end-to-end, in the same discipline as
sync_docs (ARCHCOM-7 contract §2 layers):

  L0  local clones pinned by full SHA in sync-config.yaml `api_hub.sources`
      (+ our own OpenAPI snapshot, pinned by its git blob SHA).
  L1  this script + the `api_hub:` section of scripts/sync-config.yaml
      (grouping map, selection, excludes with reasons on record).
  L2  generated corpus under viewer/src/features/docs/content/upstream/api/
      merged into provenance.json + manifest.sidecar.json.

Sections (categories.ts registry on the viewer side):
  api-overview        curated hub cover (what lives here, source map,
                      freshness rule);
  api-board           vesma-eyes board API — DETERMINISTIC rendering of
      viewer/board-openapi-snapshot.json (ru + en mirror, ME-044): path
      groups from the `board_api.groups` map, one page per group + an
      index page, built per locale (group title/about are locale mappings
      in the config; table chrome comes from RU_LABELS/EN_LABELS; the
      spec's own operation texts are EN in both locales). Hand retelling
      is FORBIDDEN: a spec change means regeneration. Provenance of every
      generated page = the spec's git blob SHA + the date of the last
      commit touching the spec (in frontmatter `source:` and in the
      sidecar provenance block) — identical for both locales.
  api-mnemos          vesma HTTP API surfaces: the upstream A2A Sessions
      API spec (docs/en|ru/architecture/a2a-sessions.md, previously outside
      every selection) + a curated map page over the full HTTP reference
      that already lives in the vesma hub (no duplicate corpus copies).
  api-agent           vesmaro-agent: the wire protocol body from the repo
      (docs/PROTOCOL.md, EN — shown under the original-language badge) + a
      curated digest of the service charter v2 with provenance.
  api-mesh            an HONEST short note: vesma-mesh has no public HTTP
      API — internal gRPC contracts only (verified against the mesh pin).

Curated bodies are authored OUTSIDE the wiped zone, in
viewer/src/features/docs/curated/api/<locale>/<path>.md (the same pattern
as sync_docs curated translations) and republished into the corpus on
every run — a missing curated file is a warning, the locale slot is
skipped.

Order of runs: `npm run sync-docs` chains sync_docs.py FIRST (it wipes
content/upstream/*, including api/) and THIS generator second. Running
gen_api_ref.py twice is byte-identical (no wall-clock anywhere), and
since ME-052 also ACROSS commits: every provenance anchor follows content
(the spec blob, upstream pins, the last change of a curated source), so
regenerating between unrelated main commits produces zero diff. Running
sync_docs.py alone leaves a consistent tree without api/ pages (the
sidecar is rebuilt from scratch there) — the npm chain is the contract.

Usage:
  python3 scripts/gen_api_ref.py sync            regenerate the api corpus
  python3 scripts/gen_api_ref.py                 (same, default command)
  python3 scripts/gen_api_ref.py check-drift     compare api_hub pins with
                                                 clone HEADs (report-only)

Exit codes: 0 ok, 1 error (bad pin, dirty clone, unmapped spec path,
config sanity, sidecar merge failure).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path
from typing import Any

import sync_docs
from sync_docs import (
    CONTENT_UPSTREAM,
    REPO_ROOT,
    SyncError,
    assemble_page,
    commit_iso,
    first_h1,
    normalize_mermaid_labels,
    resolve_pin,
    resolve_sha,
    run_git,
    split_frontmatter,
    strip_chrome,
)

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    sys.exit("gen_api_ref: PyYAML is required (python3 -m pip install pyyaml)")

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_CONFIG = SCRIPT_DIR / "sync-config.yaml"
CURATED_DIR = REPO_ROOT / "viewer" / "src" / "features" / "docs" / "curated" / "api"
API_DIR = CONTENT_UPSTREAM / "api"
PROVENANCE_NAME = "provenance.json"
SIDECAR_NAME = "manifest.sidecar.json"
HTTP_METHODS = ("get", "put", "post", "patch", "delete")

GEN_BANNER_TEMPLATE = (
    "<!-- GENERATED by gen_api_ref (api hub) from {source}@{sha12} "
    "— правки через sync-config.yaml api_hub -->"
)
GEN_SPEC_BANNER_TEMPLATE = (
    "<!-- GENERATED by gen_api_ref from board-openapi-snapshot.json blob "
    "{sha12} (v{version}) — правки = регенерация, не руками -->"
)
CURATED_BANNER_TEMPLATE = (
    "<!-- GENERATED by gen_api_ref (curated api-hub page) from {source} "
    "— правки в curated-файле, не здесь -->"
)

RU_LABELS = {
    "params": "Параметры",
    "in_path": "путь",
    "in_query": "запрос",
    "param": "Параметр",
    "where": "В",
    "type": "Тип",
    "required": "Обяз.",
    "constraints": "Ограничения",
    "required_yes": "да",
    "required_no": "нет",
    "body_required": "Тело запроса (обязательное)",
    "body_optional": "Тело запроса (необязательное)",
    "body_schema_suffix": "— схема `{name}`",
    "responses": "Ответы",
    "code": "Код",
    "schema": "Схема",
    "description": "Описание",
    "schemas_appendix": "Схемы, используемые на странице",
    "field": "Поле",
    "default": "Дефолт",
    "no_content": "—",
    # type words (render_type)
    "type_array": "массив из",
    "type_object": "объект",
    "type_string": "строка",
    "type_integer": "целое",
    "type_number": "число",
    "type_boolean": "булево",
    # item-position plurals: RU keeps the exact v1 wording (empty = base
    # word), EN pluralizes ("array of strings", not "array of string")
    "type_plural": {},
    # constraint chrome (render_constraints)
    "c_values": "значения:",
    "c_chars": "симв.",
    "c_format": "формат",
    "c_pattern": "паттерн",
    # page chrome (render_group_page + the index page)
    "generated_from": "Сгенерировано из снимка OpenAPI v{version} (эндпоинтов в разделе: {count}).",
    "snapshot_line": "Снимок OpenAPI: **{title} v{version}**, {ops} операций, {schemas} схем. Разделы справочника:",
    "index_table": ("Раздел", "Операций", "Что покрывает"),
    "index_note": (
        "Страницы разделов генерируются из снимка детерминированно "
        "(`scripts/gen_api_ref.py`): правка возможна только регенерацией. "
        "Внутри разделов — таблицы параметров, схем и ответов; тексты "
        "операций приведены из спеки как есть (EN)."
    ),
    "schema_outside": "Схема `{name}` определена вне этого раздела снимка.",
    "schema_plain": "Схема без именованных свойств (скаляр или перечисление).",
}

# ME-044: the EN mirror of the board reference. RU v1 stays byte-identical;
# EN pages share the spec provenance and differ ONLY in chrome/labels —
# operation summaries/descriptions come from the spec and are EN already.
EN_LABELS = {
    "params": "Parameters",
    "in_path": "path",
    "in_query": "query",
    "param": "Parameter",
    "where": "In",
    "type": "Type",
    "required": "Required",
    "constraints": "Constraints",
    "required_yes": "yes",
    "required_no": "no",
    "body_required": "Request body (required)",
    "body_optional": "Request body (optional)",
    "body_schema_suffix": "— schema `{name}`",
    "responses": "Responses",
    "code": "Code",
    "schema": "Schema",
    "description": "Description",
    "schemas_appendix": "Schemas used on this page",
    "field": "Field",
    "default": "Default",
    "no_content": "—",
    "type_array": "array of",
    "type_object": "object",
    "type_string": "string",
    "type_integer": "integer",
    "type_number": "number",
    "type_boolean": "boolean",
    "type_plural": {
        "string": "strings",
        "integer": "integers",
        "number": "numbers",
        "boolean": "booleans",
        "object": "objects",
    },
    "c_values": "values:",
    "c_chars": "chars",
    "c_format": "format",
    "c_pattern": "pattern",
    "generated_from": "Generated from the OpenAPI snapshot v{version} (operations in this section: {count}).",
    "snapshot_line": "OpenAPI snapshot: **{title} v{version}**, {ops} operations, {schemas} schemas. Reference sections:",
    "index_table": ("Section", "Operations", "Coverage"),
    "index_note": (
        "Section pages are generated from the snapshot deterministically "
        "(`scripts/gen_api_ref.py`): the only way to edit them is "
        "regeneration. Inside the sections: parameter, schema, and response "
        "tables; operation texts are quoted from the spec as is."
    ),
    "schema_outside": "Schema `{name}` is defined outside this section of the snapshot.",
    "schema_plain": "Schema without named properties (scalar or enum).",
}

LABELS = {"ru": RU_LABELS, "en": EN_LABELS}
BOARD_LOCALES = ("ru", "en")


# --------------------------------------------------------------------------
# config
# --------------------------------------------------------------------------

def load_api_hub_config(path: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    """(full config, api_hub section) — the GLOBAL `normalize` rules apply
    to api-hub upstream bodies exactly like to the sync corpus."""
    config = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(config, dict):
        raise SyncError(f"{path}: expected a yaml mapping")
    hub = config.get("api_hub")
    if not isinstance(hub, dict):
        raise SyncError(f"{path}: no `api_hub:` section — the api hub owns it")
    for key in ("url_prefix", "sources", "board_api", "curated"):
        if key not in hub:
            raise SyncError(f"{path}: api_hub lacks `{key}`")
    if hub["url_prefix"] != "api":
        raise SyncError(
            f"{path}: api_hub.url_prefix must stay `api` "
            f"(projects.ts registry owns the segment)"
        )
    for name, source in hub["sources"].items():
        for key in ("repo", "ref", "include"):
            if key not in source:
                raise SyncError(f"{path}: api_hub.sources.{name} lacks `{key}`")
    return config, hub


# --------------------------------------------------------------------------
# provenance pins (L0)
# --------------------------------------------------------------------------

def pin_source(name: str, source: dict[str, Any]) -> dict[str, Any]:
    """Resolve an api_hub source pin. Bodies are read from git OBJECTS of
    the pinned commit (`git show sha:path`), never from the clone's working
    tree — one clone may legitimately sit checked out at ANOTHER pin (the
    sync_docs projects share ../mnemos with a different ref), so the
    checkout state must not leak into api-hub content. No pristine check:
    dirty worktrees cannot affect object reads. ME-046: the pin must
    resolve (fetch-completeness) — an object the clone never fetched fails
    LOUD with a fetch hint, never falls through to empty output."""
    repo = (REPO_ROOT / source["repo"]).resolve()
    if not (repo / ".git").exists():
        raise SyncError(
            f"api_hub.sources.{name}: clone not found at {repo} — worktrees "
            f"need the wt/ mirror (see wt/README.md), the main checkout "
            f"resolves ../{name} directly"
        )
    sha = resolve_pin(repo, f"api_hub.sources.{name}", source["ref"])
    return {"repo_path": str(repo), "sha": sha, "commit_date": commit_iso(repo, sha)}


def spec_provenance(spec_path: Path) -> dict[str, Any]:
    """Content pin for the OpenAPI snapshot: git blob SHA + last commit date.

    A blob SHA survives our own commits unchanged — the pin follows the
    SPEC CONTENT, not the repo state (deterministic across re-runs).
    """
    if not spec_path.is_file():
        raise SyncError(f"api_hub.board_api: spec not found at {spec_path}")
    blob = hashlib.sha1(f"blob {spec_path.stat().st_size}\0".encode() + spec_path.read_bytes()).hexdigest()
    date = run_git(REPO_ROOT, "log", "-1", "--format=%cI", "--", str(spec_path.relative_to(REPO_ROOT)))
    if not date:
        date = run_git(REPO_ROOT, "log", "-1", "--format=%cI")
    return {"sha": blob, "commit_date": date}


# --------------------------------------------------------------------------
# OpenAPI → markdown (ru + en, ME-044)
# --------------------------------------------------------------------------

def locale_text(value: Any, locale: str, where: str) -> str:
    """Per-locale config text (group titles/abouts). A mapping carries one
    entry per locale — a missing key is a config bug, fail-closed (the
    overlay-anchor discipline). A plain string is shared by all locales
    (single-language authoring escape, e.g. a product name)."""
    if isinstance(value, dict):
        if locale not in value:
            raise SyncError(
                f"{where}: no `{locale}` entry — add it to the config (fail-closed)"
            )
        return str(value[locale])
    return str(value)


def schema_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def render_type(node: Any, labels: dict[str, Any]) -> str:
    """Compact localized type string; nested $refs render by name (no recursion)."""
    if node is None or isinstance(node, bool):
        return "—"
    if "$ref" in node:
        return f"`{schema_name(node['$ref'])}`"
    for combinator in ("anyOf", "oneOf", "allOf"):
        if combinator in node:
            return " | ".join(render_type(part, labels) for part in node[combinator])
    node_type = node.get("type")
    if node_type == "array":
        items = node.get("items")
        plural = (
            labels.get("type_plural", {}).get(items.get("type"))
            if isinstance(items, dict)
            else None
        )
        inner = plural or render_type(items, labels)
        return f"{labels['type_array']} {inner}"
    if node_type in ("object", "string", "integer", "number", "boolean"):
        return str(labels[f"type_{node_type}"])
    if node_type == "null":
        return "null"
    return str(node_type or "—")


def render_constraints(node: dict[str, Any], labels: dict[str, Any]) -> str:
    parts: list[str] = []
    if "enum" in node:
        parts.append(f"{labels['c_values']} " + ", ".join(f"`{v}`" for v in node["enum"]))
    if "maxLength" in node:
        parts.append(f"≤ {node['maxLength']} {labels['c_chars']}")
    if "minLength" in node:
        parts.append(f"≥ {node['minLength']} {labels['c_chars']}")
    if "maximum" in node:
        parts.append(f"≤ {node['maximum']}")
    if "minimum" in node:
        parts.append(f"≥ {node['minimum']}")
    if "format" in node:
        parts.append(f"{labels['c_format']} {node['format']}")
    if "pattern" in node:
        parts.append(f"{labels['c_pattern']} `{node['pattern']}`")
    if node.get("description"):
        parts.append(str(node["description"]))
    return "; ".join(parts)


def schema_property_rows(schema: dict[str, Any], labels: dict[str, Any]) -> list[list[str]]:
    rows: list[list[str]] = []
    for name, prop in (schema.get("properties") or {}).items():
        required = name in (schema.get("required") or [])
        default = prop.get("default")
        rows.append(
            [
                f"`{name}`",
                render_type(prop, labels),
                labels["required_yes"] if required else labels["required_no"],
                labels["no_content"] if default is None else f"`{json.dumps(default, ensure_ascii=False)}`",
                render_constraints(prop, labels),
            ]
        )
    return rows


def md_table(header: list[str], rows: list[list[str]]) -> str:
    """GFM table with cell-level pipe escaping — type unions like
    ``целое | null`` or enum values must never split a row."""

    def cell(value: str) -> str:
        return str(value).replace("|", "\\|")

    lines = [
        "| " + " | ".join(cell(h) for h in header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    lines.extend("| " + " | ".join(cell(v) for v in row) + " |" for row in rows)
    return "\n".join(lines)


def response_schema_ref(response: dict[str, Any]) -> str | None:
    for media in (response.get("content") or {}).values():
        ref = (media.get("schema") or {}).get("$ref")
        if ref:
            return schema_name(ref)
    return None


def render_operation(
    method: str, path: str, op: dict[str, Any], labels: dict[str, Any]
) -> tuple[str, list[str]]:
    """One operation section + the schema names directly referenced."""
    lines: list[str] = [f"### `{method.upper()}` `{path}`"]
    if op.get("summary"):
        lines.append("")
        lines.append(f"**{op['summary']}**")
    if op.get("description"):
        lines.append("")
        lines.append(str(op["description"]))

    params = [p for p in op.get("parameters", []) if p.get("in") in ("path", "query")]
    if params:
        rows = [
            [
                f"`{p['name']}`",
                labels["in_path"] if p.get("in") == "path" else labels["in_query"],
                render_type(p.get("schema") or {}, labels),
                labels["required_yes"] if p.get("required") else labels["required_no"],
                render_constraints(p.get("schema") or {}, labels) or str(p.get("description") or ""),
            ]
            for p in params
        ]
        lines.append("")
        lines.append(f"**{labels['params']}**")
        lines.append("")
        lines.append(
            md_table(
                [labels["param"], labels["where"], labels["type"], labels["required"], labels["constraints"]],
                rows,
            )
        )

    refs: list[str] = []
    body = op.get("requestBody") or {}
    body_schema = None
    for media in (body.get("content") or {}).values():
        ref = (media.get("schema") or {}).get("$ref")
        if ref:
            body_schema = schema_name(ref)
            break
    if body:
        title = (
            labels["body_required"] if body.get("required") else labels["body_optional"]
        )
        suffix = str(labels["body_schema_suffix"]).format(name=body_schema) if body_schema else ""
        lines.append("")
        lines.append(f"**{title}**" + (f" {suffix}" if suffix else ""))
        if body_schema:
            refs.append(body_schema)

    if op.get("responses"):
        lines.append("")
        lines.append(f"**{labels['responses']}**")
        lines.append("")
        rows = []
        for code in sorted(op["responses"], key=str):
            response = op["responses"][code]
            ref = response_schema_ref(response)
            if ref and ref not in refs:
                refs.append(ref)
            rows.append(
                [
                    f"`{code}`",
                    f"`{ref}`" if ref else labels["no_content"],
                    str(response.get("description") or ""),
                ]
            )
        lines.append(
            md_table([labels["code"], labels["schema"], labels["description"]], rows)
        )
    return "\n".join(lines), refs


def render_group_page(
    *,
    group: dict[str, Any],
    operations: list[tuple[str, str, dict[str, Any]]],
    schemas: dict[str, Any],
    spec_meta: dict[str, Any],
    locale: str,
) -> str:
    """The markdown body of one board-API group page (ru or en)."""
    labels = LABELS[locale]
    title = locale_text(group["title"], locale, f"board_api.groups[{group['slug']}].title")
    about = locale_text(group["about"], locale, f"board_api.groups[{group['slug']}].about") if group.get("about") else ""
    lines: list[str] = [f"# {title}", ""]
    if about:
        lines.append(about)
        lines.append("")
    lines.append(str(labels["generated_from"]).format(version=spec_meta["version"], count=len(operations)))
    lines.append("")
    for method, path, op in operations:
        section, refs = render_operation(method, path, op, labels)
        lines.append(section)
        lines.append("")
    referenced = sorted(
        {
            ref
            for _, _, op in operations
            for ref in collect_refs(op)
        }
    )
    if referenced:
        lines.append(f"## {labels['schemas_appendix']}")
        lines.append("")
        for name in referenced:
            schema = schemas.get(name)
            lines.append(f"### `{name}`")
            lines.append("")
            if schema is None:
                lines.append(str(labels["schema_outside"]).format(name=name))
                lines.append("")
                continue
            rows = schema_property_rows(schema, labels)
            if rows:
                lines.append(
                    md_table(
                        [labels["field"], labels["type"], labels["required"], labels["default"], labels["constraints"]],
                        rows,
                    )
                )
            else:
                lines.append(str(labels["schema_plain"]))
            lines.append("")
    return "\n".join(lines).rstrip("\n")


def collect_refs(op: dict[str, Any]) -> list[str]:
    refs: list[str] = []
    body = op.get("requestBody") or {}
    for media in (body.get("content") or {}).values():
        ref = (media.get("schema") or {}).get("$ref")
        if ref:
            refs.append(schema_name(ref))
    for response in (op.get("responses") or {}).values():
        ref = response_schema_ref(response)
        if ref:
            refs.append(ref)
    return refs


def build_board_pages(
    board_api: dict[str, Any], prov: dict[str, Any]
) -> tuple[list[dict[str, Any]], int]:
    """Deterministic spec → pages pipeline, one page-set per BOARD_LOCALE
    (ME-044: ru + en mirror). Unmapped path = DRIFT fail. Both locale sets
    share the spec provenance; only labels/titles differ."""
    spec_path = REPO_ROOT / board_api["spec"]
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    schemas = (spec.get("components") or {}).get("schemas") or {}
    info = spec.get("info") or {}
    version = str(info.get("version") or "?")

    groups: dict[str, dict[str, Any]] = {g["slug"]: g for g in board_api["groups"]}
    prefix_map: dict[str, str] = {}
    for group in board_api["groups"]:
        for prefix in group["prefixes"]:
            if prefix in prefix_map:
                raise SyncError(
                    f"api_hub.board_api: prefix `{prefix}` mapped twice — fix the config"
                )
            prefix_map[prefix] = group["slug"]

    by_group: dict[str, list[tuple[str, str, dict[str, Any]]]] = {slug: [] for slug in groups}
    total_ops = 0
    for path in sorted(spec.get("paths", {})):
        first = path.strip("/").split("/")[1] if path.startswith("/api/") else None
        if first is None:
            raise SyncError(f"api_hub.board_api: path {path!r} is outside /api/ — unmapped")
        slug = prefix_map.get(first)
        if slug is None:
            raise SyncError(
                f"api_hub.board_api: path prefix `{first}` ({path}) is not in the "
                f"groups map — SPEC DRIFT: add it to api_hub.board_api.groups in "
                f"sync-config.yaml (fail-closed, the sync overlay discipline)"
            )
        for method in HTTP_METHODS:
            op = spec["paths"][path].get(method)
            if isinstance(op, dict):
                by_group[slug].append((method, path, op))
                total_ops += 1

    spec_meta = {"version": version}
    pages: list[dict[str, Any]] = []
    banner = GEN_SPEC_BANNER_TEMPLATE.format(sha12=prov["sha"][:12], version=version)
    extra_fields = [("source", f"spec@{prov['sha'][:12]}"), ("spec_version", version)]
    provenance = {
        "repo": "vesma-eyes",
        "source_path": board_api["spec"],
        "sha": prov["sha"],
        "commit_date": prov["commit_date"],
    }

    for locale in BOARD_LOCALES:
        labels = LABELS[locale]

        # --- index page -------------------------------------------------
        index_slug = board_api["index_slug"]
        index_group = groups[index_slug]
        index_title = locale_text(
            index_group["title"], locale, f"board_api.groups[{index_slug}].title"
        )
        index_about = (
            locale_text(index_group["about"], locale, f"board_api.groups[{index_slug}].about")
            if index_group.get("about")
            else ""
        )
        rows = []
        for group in board_api["groups"]:
            if group["slug"] == index_slug:
                continue
            group_title = locale_text(
                group["title"], locale, f"board_api.groups[{group['slug']}].title"
            )
            group_about = (
                locale_text(group["about"], locale, f"board_api.groups[{group['slug']}].about")
                if group.get("about")
                else ""
            )
            rows.append(
                [f"[{group_title}](api/{group['slug']})", str(len(by_group[group["slug"]])), group_about]
            )
        index_body = "\n".join(
            [
                f"# {index_title}",
                "",
                index_about,
                "",
                str(labels["snapshot_line"]).format(
                    title=info.get("title", "vesma-eyes"),
                    version=version,
                    ops=total_ops,
                    schemas=len(schemas),
                ),
                "",
                md_table(list(labels["index_table"]), rows),
                "",
                f"> {labels['index_note']}",
            ]
        )
        pages.append(
            {
                "path": f"{index_slug}.md",
                "locale": locale,
                "title": index_title,
                "category": board_api["category"],
                "order": int(index_group["order"]),
                "body": index_body,
                "banner": banner,
                "extra_fields": extra_fields,
                "provenance": provenance,
                "kind": "openapi-generated",
            }
        )

        # --- one page per group ------------------------------------------
        for group in board_api["groups"]:
            if group["slug"] == index_slug:
                continue
            group_title = locale_text(
                group["title"], locale, f"board_api.groups[{group['slug']}].title"
            )
            body = render_group_page(
                group=group,
                operations=by_group[group["slug"]],
                schemas=schemas,
                spec_meta=spec_meta,
                locale=locale,
            )
            pages.append(
                {
                    "path": f"{group['slug']}.md",
                    "locale": locale,
                    "title": group_title,
                    "category": board_api["category"],
                    "order": int(group["order"]),
                    "body": body,
                    "banner": banner,
                    "extra_fields": extra_fields,
                    "provenance": provenance,
                    "kind": "openapi-generated",
                }
            )
    return pages, total_ops


# --------------------------------------------------------------------------
# repo sources (upstream md bodies)
# --------------------------------------------------------------------------

def build_source_pages(
    name: str,
    source: dict[str, Any],
    pin: dict[str, Any],
    corpus_slugs: set[str],
    normalize: dict[str, Any],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Included md files from one pinned clone, sync_docs L1 rules applied."""
    repo = Path(pin["repo_path"])
    locale_dirs: dict[str, str] = source.get("locale_dirs") or {"en": "docs"}
    web_base = source.get("web_base", "")
    stats: dict[str, list[Any]] = {
        "included_slugs": sorted(corpus_slugs),
        "asset_copies": [],
        "images": [],
        "dangling_slugs": [],
        "github_links": [],
        "escapes": [],
        "missing_targets": [],
        "overlays_applied": [],
    }
    pages: list[dict[str, Any]] = []
    report: dict[str, Any] = {"skipped": []}

    for entry in source["include"]:
        for locale, locale_dir in sorted(locale_dirs.items()):
            object_path = f"{pin['sha']}:{locale_dir}/{entry['path']}"
            try:
                raw = run_git(repo, "show", object_path)
            except SyncError:
                report["skipped"].append(f"{locale}/{entry['path']}: missing at pin {pin['sha'][:12]}")
                continue
            body = strip_chrome(raw, normalize)
            body = normalize_mermaid_labels(body)
            rewriter = sync_docs.Rewriter(
                project=name,
                repo=repo,
                sha=pin["sha"],
                web_base=web_base,
                locale_dirs=locale_dirs,
                source_dir="/".join(posix_dir(locale_dir, entry["path"])),
                assets_out=sync_docs.ASSETS_UPSTREAM,
                stats=stats,
            )
            body = rewriter.rewrite(body)
            title = entry.get("title") or {}
            if isinstance(title, dict):
                title = title.get(locale) or first_h1(body) or entry["path"]
            note = entry.get("note") or {}
            if isinstance(note, dict):
                note = note.get(locale)
            slug_tail = entry["slug"].strip("/")
            pages.append(
                {
                    "path": f"{slug_tail}.md",
                    "locale": locale,
                    "title": str(title),
                    "category": str(entry["category"]),
                    "order": int(entry["order"]),
                    "body": body,
                    "banner": GEN_BANNER_TEMPLATE.format(source=name, sha12=pin["sha"][:12]),
                    "extra_fields": [("source", f"{name}@{pin['sha'][:12]}")],
                    "note": str(note).strip() if note else None,
                    "provenance": {
                        "repo": name,
                        "source_path": f"{locale_dir}/{entry['path']}",
                        "sha": pin["sha"],
                        "commit_date": pin["commit_date"],
                    },
                    "kind": "upstream",
                }
            )
    report["dangling_slugs"] = sorted(set(stats["dangling_slugs"]))
    report["github_links"] = sorted(set(stats["github_links"]))
    report["escapes"] = sorted(set(stats["escapes"]))
    report["missing_targets"] = sorted(set(stats["missing_targets"]))
    return pages, report


def posix_dir(*parts: str) -> list[str]:
    import posixpath

    directory = posixpath.dirname("/".join(parts))
    return directory.split("/") if directory else []


# --------------------------------------------------------------------------
# curated pages (our layer, outside the wiped zone)
# --------------------------------------------------------------------------

def build_curated_pages(
    curated: list[dict[str, Any]], pins: dict[str, dict[str, Any]]
) -> tuple[list[dict[str, Any]], list[str]]:
    pages: list[dict[str, Any]] = []
    warnings: list[str] = []
    for entry in curated:
        slug_tail = entry["slug"].strip("/")
        published: dict[str, dict[str, Any]] = {}
        for locale in ("ru", "en"):
            curated_file = CURATED_DIR / locale / f"{slug_tail}.md"
            if not curated_file.is_file():
                warnings.append(f"curated file missing: {curated_file} (locale skipped)")
                continue
            meta, body = split_frontmatter(
                curated_file.read_text(encoding="utf-8"), str(curated_file)
            )
            body = normalize_mermaid_labels(body)
            title = meta.get("title") or first_h1(body) or slug_tail
            published[locale] = {
                "path": f"{slug_tail}.md",
                "locale": locale,
                "title": title,
                "category": str(entry["category"]),
                "order": int(entry["order"]),
                "body": body,
                "banner": CURATED_BANNER_TEMPLATE.format(
                    source=f"curated/api/{locale}/{slug_tail}.md"
                ),
                "extra_fields": [],
                "provenance": curated_provenance(entry, pins),
                "kind": "curated",
            }
        if not published:
            warnings.append(f"curated page {slug_tail}: no locales published")
            continue
        pages.extend(published[locale] for locale in sorted(published))
    return pages, warnings


def hub_internal_provenance(
    slug_tail: str,
    *,
    repo: Path | None = None,
    curated_dir: Path | None = None,
) -> dict[str, str]:
    """Provenance anchor for hub-internal curated pages (ME-052).

    The page's own curated sources are the stable thing it was verified
    against, so the anchor is the LAST COMMIT THAT CHANGED THEM (either
    locale file) — its SHA and date. The pre-ME-052 behavior pinned repo
    HEAD, which restamped verified-at on every unrelated main commit
    (noisy diff: regeneration between commits was not byte-stable).
    ADR 0016 §7 canon: honest freshness follows the SOURCE, not the repo
    state. Fallback when no curated file has history yet (freshly added,
    uncommitted): generation HEAD, the only honest thing that exists."""
    if repo is None:
        repo = REPO_ROOT
    if curated_dir is None:
        curated_dir = CURATED_DIR
    source_path = f"curated/api/{{ru,en}}/{slug_tail}.md"
    paths = [curated_dir / locale / f"{slug_tail}.md" for locale in ("ru", "en")]
    existing = [p for p in paths if p.is_file()]
    log = ""
    if existing:
        try:
            rels = [str(p.relative_to(repo)) for p in existing]
        except ValueError:  # curated dir outside the repo — config bug
            raise SyncError(
                f"curated/{slug_tail}: curated dir {curated_dir} is not inside "
                f"{repo} — cannot anchor provenance"
            ) from None
        log = run_git(repo, "log", "-1", "--format=%H%x00%cI", "--", *rels)
    if not log:
        head = run_git(repo, "rev-parse", "HEAD")
        return {
            "repo": "vesma-eyes",
            "source_path": source_path,
            "sha": head,
            "commit_date": run_git(repo, "log", "-1", "--format=%cI"),
        }
    sha, date = log.split("\x00")
    return {
        "repo": "vesma-eyes",
        "source_path": source_path,
        "sha": sha,
        "commit_date": date,
    }


def curated_provenance(entry: dict[str, Any], pins: dict[str, dict[str, Any]]) -> dict[str, str]:
    """Curated pages carry the pin of the source they were verified against."""
    verify = entry.get("verified_against") or {}
    pin = pins.get(verify.get("source", ""))
    if pin and verify.get("sha") == "pin":
        return {
            "repo": verify["source"],
            "source_path": str(verify.get("path", "")),
            "sha": pin["sha"],
            "commit_date": pin["commit_date"],
        }
    # Hub-internal curation (ME-052): pin the last actual change of the
    # page's curated sources — a HEAD pin restamped on every commit.
    return hub_internal_provenance(str(entry["slug"]).strip("/"))


# --------------------------------------------------------------------------
# L2 assembly + sidecar/provenance merge
# --------------------------------------------------------------------------

def page_to_file(page: dict[str, Any], url_prefix: str) -> tuple[Path, str]:
    slug = f"{url_prefix}/{page['path'][: -len('.md')]}"
    fields = [
        ("title", str(page["title"])),
        ("slug", slug),
        ("category", str(page["category"])),
        ("order", str(int(page["order"]))),
        ("last_verified", str(page["provenance"]["commit_date"])[:10]),
    ] + list(page.get("extra_fields") or [])
    md = assemble_page(
        fields=fields,
        banner=page["banner"],
        note=page.get("note"),
        body=page["body"],
    )
    dest = CONTENT_UPSTREAM / url_prefix / page["locale"] / page["path"]
    return dest, md


def merge_manifests(
    pages: list[dict[str, Any]], url_prefix: str, hub: dict[str, Any], pins: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    """Merge api pages into provenance.json + manifest.sidecar.json."""
    provenance_path = CONTENT_UPSTREAM / PROVENANCE_NAME
    sidecar_path = CONTENT_UPSTREAM / SIDECAR_NAME
    if not provenance_path.is_file() or not sidecar_path.is_file():
        raise SyncError(
            "api hub: provenance.json/manifest.sidecar.json missing — run "
            "sync_docs.py first (`npm run sync-docs` chains both)"
        )
    provenance = json.loads(provenance_path.read_text(encoding="utf-8"))
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))

    files = {
        slug: entry
        for slug, entry in provenance.get("files", {}).items()
        if not slug.startswith(f"{url_prefix}/")
    }
    sidecar_pages = {
        entry["slug"]: entry
        for entry in sidecar.get("pages", [])
        if not entry["slug"].startswith(f"{url_prefix}/")
    }

    by_slug: dict[str, dict[str, Any]] = {}
    for page in pages:
        slug = f"{url_prefix}/{page['path'][: -len('.md')]}"
        by_slug.setdefault(slug, {})[page["locale"]] = page

    for slug in sorted(by_slug):
        locales = by_slug[slug]
        first = locales[sorted(locales)[0]]
        titles = {loc: str(locales[loc]["title"]) for loc in sorted(locales)}
        files[slug] = {
            loc: {
                "repo": locales[loc]["provenance"]["repo"],
                "source_path": locales[loc]["provenance"]["source_path"],
                "sha": locales[loc]["provenance"]["sha"],
                "commit_date": locales[loc]["provenance"]["commit_date"],
                "synced_at": locales[loc]["provenance"]["commit_date"],
                "locale": loc,
                "kind": locales[loc]["kind"],
            }
            for loc in sorted(locales)
        }
        sidecar_pages[slug] = {
            "slug": slug,
            "titles": titles,
            "category": str(first["category"]),
            "order": int(first["order"]),
            "lastVerified": str(first["provenance"]["commit_date"])[:10],
            "locales": sorted(locales),
            "provenance": dict(first["provenance"]),
            "contentClass": {loc: "corpus" for loc in sorted(locales)},
        }

    projects = dict(provenance.get("projects") or {})
    projects["api_hub"] = {
        "board_api_spec": hub["board_api"]["spec"],
        "board_api_blob_sha": pins["__spec__"]["sha"],
        "sources": {
            name: {"repo": hub["sources"][name]["repo"], "ref": hub["sources"][name]["ref"], "sha": pins[name]["sha"]}
            for name in sorted(hub["sources"])
            if name in pins
        },
    }
    all_dates = [
        pin["commit_date"]
        for key, pin in pins.items()
        if key != "__spec__"
    ] + [pins["__spec__"]["commit_date"]]
    provenance_out = {
        "version": provenance.get("version", 1),
        "generated_by": "scripts/sync_docs.py + scripts/gen_api_ref.py",
        "synced_at": max(all_dates) if all_dates else None,
        "projects": projects,
        "files": dict(sorted(files.items())),
    }
    source_shas = dict(sidecar.get("source_shas") or {})
    source_shas.update(
        {
            f"api/{name}": pins[name]["sha"]
            for name in sorted(hub["sources"])
            if name in pins
        }
    )
    sidecar_out = {
        "version": sidecar.get("version", 1),
        "generated_by": "scripts/sync_docs.py + scripts/gen_api_ref.py",
        "source_shas": source_shas,
        "pages": [sidecar_pages[slug] for slug in sorted(sidecar_pages)],
    }
    provenance_path.write_text(
        json.dumps(provenance_out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    sidecar_path.write_text(
        json.dumps(sidecar_out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return {"pages": len(by_slug), "files": len(files)}


# --------------------------------------------------------------------------
# sync
# --------------------------------------------------------------------------

def sync(config: dict[str, Any], hub: dict[str, Any]) -> dict[str, Any]:
    normalize = sync_docs.normalize_rules(config)
    pins: dict[str, dict[str, Any]] = {}
    for name, source in hub["sources"].items():
        pins[name] = pin_source(name, source)
    pins["__spec__"] = spec_provenance(REPO_ROOT / hub["board_api"]["spec"])

    sidecar_slugs: set[str] = set()
    sidecar_path = CONTENT_UPSTREAM / SIDECAR_NAME
    if sidecar_path.is_file():
        existing = json.loads(sidecar_path.read_text(encoding="utf-8"))
        sidecar_slugs = {entry["slug"] for entry in existing.get("pages", [])}

    report: dict[str, Any] = {"sources": {}, "skipped": [], "warnings": []}

    board_pages, total_ops = build_board_pages(hub["board_api"], pins["__spec__"])
    report["board_api"] = {
        "pages": len(board_pages),
        "pages_per_locale": len(board_pages) // len(BOARD_LOCALES),
        "locales": list(BOARD_LOCALES),
        "operations": total_ops,
        "spec_blob": pins["__spec__"]["sha"][:12],
        "spec_version": json.loads((REPO_ROOT / hub["board_api"]["spec"]).read_text(encoding="utf-8"))["info"]["version"],
    }

    own_slugs = {
        f"{hub['url_prefix']}/{page['path'][: -len('.md')]}" for page in board_pages
    }
    corpus_slugs = sidecar_slugs | own_slugs

    pages = list(board_pages)
    for name, source in sorted(hub["sources"].items()):
        source_pages, source_report = build_source_pages(
            name, source, pins[name], corpus_slugs, normalize
        )
        pages.extend(source_pages)
        corpus_slugs |= {
            f"{hub['url_prefix']}/{page['path'][: -len('.md')]}" for page in source_pages
        }
        report["sources"][name] = {
            "sha": pins[name]["sha"],
            "pages": len(source_pages),
            **source_report,
        }

    curated_pages, warnings = build_curated_pages(hub["curated"], pins)
    pages.extend(curated_pages)
    report["warnings"].extend(warnings)

    # --- phase B: wipe the api subtree, write everything --------------------
    if API_DIR.exists():
        shutil.rmtree(API_DIR)
    for page in pages:
        dest, md = page_to_file(page, hub["url_prefix"])
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(md, encoding="utf-8")

    merged = merge_manifests(pages, hub["url_prefix"], hub, pins)

    # --- reuse the sync_docs contentClass gate over the FULL merged tree ----
    provenance = json.loads((CONTENT_UPSTREAM / PROVENANCE_NAME).read_text(encoding="utf-8"))
    sidecar = json.loads((CONTENT_UPSTREAM / SIDECAR_NAME).read_text(encoding="utf-8"))
    sidecar_by_slug = {entry["slug"]: entry for entry in sidecar["pages"]}
    sync_docs._verify_content_class_gate(sidecar_by_slug, provenance["files"], CONTENT_UPSTREAM)

    report.update(
        {
            "pages": merged["pages"],
            "provenance_files": merged["files"],
            "pins": {
                key: pin["sha"] if key != "__spec__" else pin["sha"]
                for key, pin in pins.items()
            },
        }
    )
    return report


# --------------------------------------------------------------------------
# drift
# --------------------------------------------------------------------------

def check_drift(hub: dict[str, Any]) -> None:
    """Report-only. NOTE: api-hub bodies are read from git OBJECTS of the
    pin (see pin_source), so a differing clone HEAD is INFORMATIONAL — the
    ../mnemos and ../mnemos-mesh clones are SHARED with the sync_docs
    projects, whose pins legitimately own the checkout state."""
    for name, source in sorted(hub["sources"].items()):
        repo = (REPO_ROOT / source["repo"]).resolve()
        pinned = resolve_pin(repo, f"api/{name}", source["ref"])
        head = resolve_sha(repo, "HEAD")
        same = "OK" if head == pinned else "checkout differs (shared clone; content unaffected)"
        print(f"[api/{name}] pin {pinned[:12]}, clone HEAD {head[:12]}: {same}")
        if tracked_dirty_status(repo):
            print("    WARNING: clone has tracked modifications")
    spec = spec_provenance(REPO_ROOT / hub["board_api"]["spec"])
    print(
        f"[api/board] spec blob {spec['sha'][:12]} "
        f"(last spec commit {spec['commit_date'][:10]})"
    )


def tracked_dirty_status(repo: Path) -> bool:
    return bool(sync_docs.tracked_dirty(repo))


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "command", nargs="?", choices=("sync", "check-drift"), default="sync",
        help="sync (default) regenerates the api corpus; check-drift is report-only",
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args(argv)

    try:
        config, hub = load_api_hub_config(args.config)
        if args.command == "check-drift":
            check_drift(hub)
            return 0
        report = sync(config, hub)
    except SyncError as error:
        print(f"gen_api_ref: {error}", file=sys.stderr)
        return 1
    board = report["board_api"]
    print(
        f"[api/board] spec blob {board['spec_blob']} v{board['spec_version']}: "
        f"{board['operations']} операций → {board['pages']} страниц "
        f"({'+'.join(board['locales'])}, по {board['pages_per_locale']})"
    )
    for name, info in report["sources"].items():
        print(
            f"[api/{name}] pinned {info['sha'][:12]}: {info['pages']} страниц; "
            f"github-ссылок {len(info.get('github_links', []))}, "
            f"dangling {info.get('dangling_slugs', [])}"
        )
        for skip in info.get("skipped", []):
            print(f"  [skip] {skip}")
    for warning in report["warnings"]:
        print(f"[warn] {warning}")
    print(
        f"total: {report['pages']} api-страниц в сайдкаре "
        f"({report['provenance_files']} записей provenance); "
        f"contentClass gate пройден"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
