#!/usr/bin/env python3
"""Docs upstream import pipeline — layer L1 (ARCHCOM-7 contract 2026-09-23).

Reads local upstream clones pinned by SHA (L0), applies the declarative
selection/normalization/overlay rules from scripts/sync-config.yaml, and
regenerates the L2 corpus in the viewer docs tree:

  viewer/src/features/docs/content/upstream/<project>/<locale>/<path>.md
  viewer/src/features/docs/content/upstream/provenance.json
  viewer/src/features/docs/content/upstream/manifest.sidecar.json
  viewer/src/features/docs/assets/upstream/<project>/<repo-relative-path>

Curated translations (our layer, e.g. mnemos-mesh ru): authored under
viewer/src/features/docs/curated/<project>/<locale>/<path>.md (outside the
wiped zone) and republished into the L2 locale slot on every sync —
provenance kind "curated-translation". A missing curated file is a warning,
never a failure.

L2 is GENERATED — never hand-edited. Style fixes go through `overlays` in
sync-config.yaml; an overlay anchor that no longer matches fails the sync
(upstream drift signal, contract §6.3). The corpus is byte-stable across
re-runs on the same pins (idempotency gate): no wall-clock values are
written — `synced_at` carries the pinned commit's ISO date instead.

Usage:
  python3 scripts/sync_docs.py sync           regenerate L2 (default)
  python3 scripts/sync_docs.py --check-drift  compare pins with clone HEADs
  python3 scripts/sync_docs.py check-drift    (same, subcommand form)

Exit codes: 0 ok, 1 sync/drift error (bad pin, dirty clone, clone HEAD off
the pin — ME-046 guard, fetch-incomplete clone, overlay drift, config
sanity).
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import posixpath
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    sys.exit("sync_docs: PyYAML is required (python3 -m pip install pyyaml)")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_CONFIG = SCRIPT_DIR / "sync-config.yaml"
DOCS_DIR = REPO_ROOT / "viewer" / "src" / "features" / "docs"
CONTENT_UPSTREAM = DOCS_DIR / "content" / "upstream"
ASSETS_UPSTREAM = DOCS_DIR / "assets" / "upstream"
PROVENANCE_NAME = "provenance.json"
SIDECAR_NAME = "manifest.sidecar.json"
BANNER_TEMPLATE = (
    "<!-- GENERATED by sync_docs from {project}@{sha} "
    "— правки через sync-config.yaml overlay -->"
)
CURATED_BANNER_TEMPLATE = (
    "<!-- GENERATED by sync_docs (curated translation of {project}@{sha}) from "
    "{source} — правки в curated-файле, не здесь -->"
)
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".avif", ".ico"}
MD_EXT = ".md"
HEADING1_RE = re.compile(r"^#\s+(.+?)\s*#*\s*$")
LINK_RE = re.compile(r"(?<!\!)\[([^\]]*)\]\(([^)\s]+)\)")
IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)\)")
EXTERNAL_TARGET_RE = re.compile(r"^(https?:)?//|^mailto:|^data:")

# Defaults applied when sync-config.yaml omits the `normalize` section.
DEFAULT_NORMALIZE: dict[str, Any] = {
    "strip_lines_matching": [],
    "strip_html_comment_lines": True,
    "collapse_blank_lines": 2,
}


class SyncError(RuntimeError):
    """Fatal pipeline error (bad pin, dirty clone, overlay drift, config)."""


# --------------------------------------------------------------------------
# git plumbing (L0)
# --------------------------------------------------------------------------

def run_git(repo: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise SyncError(
            f"git -C {repo} {' '.join(args)} failed: {proc.stderr.strip()}"
        )
    return proc.stdout.strip()


def resolve_sha(repo: Path, ref: str) -> str:
    """Full SHA for a ref (SHA, branch, tag) at the current clone state."""
    sha = run_git(repo, "rev-parse", "--verify", f"{ref}^{{commit}}")
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise SyncError(f"{repo}: ref {ref!r} did not resolve to a commit SHA")
    return sha


def tracked_dirty(repo: Path) -> list[str]:
    """Tracked modifications only — untracked files don't affect the SHA."""
    out = run_git(repo, "status", "--porcelain")
    return [
        line
        for line in out.splitlines()
        if line.strip() and not line.startswith("??")
    ]


def assert_pristine(repo: Path, project: str) -> None:
    dirty = tracked_dirty(repo)
    if dirty:
        preview = "\n".join(dirty[:10])
        raise SyncError(
            f"{project}: clone {repo} has tracked modifications — refusing to "
            f"sync so the pinned SHA stays honest. Clean or commit there "
            f"first:\n{preview}"
        )


def resolve_pin(repo: Path, where: str, ref: str) -> str:
    """Resolve a pinned ref with an actionable error (ME-046).

    A pin whose object is absent from the clone (fetch-incomplete wt/
    mirror) makes `git rev-parse` fail with a generic "Needed a single
    revision" — wrap it so the operator is told to FETCH the clone first.
    Used by both sync_docs and gen_api_ref (object access there).
    """
    try:
        return resolve_sha(repo, ref)
    except SyncError as error:
        raise SyncError(
            f"{where}: pin {ref!r} does not resolve in clone {repo} — the "
            f"clone is fetch-incomplete for this pin. Update it first: "
            f"git -C {repo} fetch --all --tags. git said: {error}"
        ) from error


def assert_head_at_pin(repo: Path, project: str, ref: str, pinned: str) -> None:
    """HEAD==pin guard (ME-046, incident 2026-09-29).

    sync() reads the clone's WORKING TREE (not git objects), so provenance
    is honest only when the checkout sits exactly at the pinned commit.
    A clone left at a previous commit while the config pin moved forward
    would silently publish stale content under the new pin — refuse that.
    """
    head = resolve_sha(repo, "HEAD")
    if head != pinned:
        raise SyncError(
            f"{project}: clone {repo} is at HEAD {head[:7]} but config pins "
            f"{ref} ({pinned[:7]}) — sync reads the clone's working tree, so "
            f"the corpus would not match its provenance. Detach the clone: "
            f"git -C {repo} checkout {pinned}"
        )


def commit_iso(repo: Path, sha: str) -> str:
    return run_git(repo, "log", "-1", "--format=%cI", sha)


# --------------------------------------------------------------------------
# config
# --------------------------------------------------------------------------

def load_config(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise SyncError(f"config not found: {path}")
    config = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(config, dict) or not config.get("projects"):
        raise SyncError(f"{path}: expected a non-empty `projects:` mapping")
    for name, project in config["projects"].items():
        for key in ("repo", "ref", "locale_dirs", "include"):
            if key not in project:
                raise SyncError(f"{path}: project {name} lacks `{key}`")
        if not project["locale_dirs"]:
            raise SyncError(f"{path}: project {name} has empty locale_dirs")
    return config


def validate_selection(project_name: str, project: dict[str, Any]) -> None:
    """Contract §6.6: exclude entries must never overlap include entries."""
    included = {entry["path"] for entry in project["include"]}
    for rule in project.get("exclude", []) or []:
        excluded = rule["path"].rstrip("/")
        for inc in included:
            if inc == excluded or inc.startswith(excluded + "/"):
                raise SyncError(
                    f"{project_name}: include {inc!r} overlaps exclude "
                    f"{rule['path']!r} — fix sync-config.yaml"
                )


def normalize_rules(config: dict[str, Any]) -> dict[str, Any]:
    rules = dict(DEFAULT_NORMALIZE)
    rules.update(config.get("normalize") or {})
    return rules


# mermaid labels: a literal two-character `\n` (backslash + 'n') inside an
# upstream label is an authoring artifact of the source generator. The
# canonical in-label line break (and what mermaid's own line-splitting
# handles: rendering-util splits on /\\n|\n|<br\s*\/?>/ — verified against
# the pinned mermaid@11.17.2) is `<br/>`. Unquoted labels keep their text
# form: quoting a label to carry `<br/>` would silently change shape
# syntax (`DB[(vesma store)]` is a cylinder only unquoted) — so the
# transform replaces the escape in place and never rewrites label delimiters
# (ME-010, АРХКОМ ADR-0020 L1 mandate). Deterministic and idempotent:
# `<br/>` survives a second pass unchanged.
MERMAID_FENCE_RE = re.compile(r"```mermaid[^\n]*\n(.*?)```", re.DOTALL)
MERMAID_LABEL_BREAK_RE = re.compile(r"\\n")


def normalize_mermaid_labels(text: str) -> str:
    """Convert literal `\\n` in mermaid labels to `<br/>` (L1, ME-010).

    Applies ONLY inside ```mermaid fences — other fences (json, yaml, text)
    carry the two-character sequence verbatim as data and must not change.
    Second run is a no-op: `<br/>` contains no `\\n` sequence.
    """
    def fix_block(match: re.Match[str]) -> str:
        block = match.group(1)
        if MERMAID_LABEL_BREAK_RE.search(block):
            return "```mermaid\n" + MERMAID_LABEL_BREAK_RE.sub("<br/>", block) + "```"
        return match.group(0)

    return MERMAID_FENCE_RE.sub(fix_block, text)


# --------------------------------------------------------------------------
# L1 text transforms
# --------------------------------------------------------------------------

def strip_chrome(text: str, rules: dict[str, Any]) -> str:
    """Cut upstream chrome: language switchers and pure html-comment lines."""
    kept: list[str] = []
    patterns = rules.get("strip_lines_matching") or []
    strip_comments = bool(rules.get("strip_html_comment_lines"))
    for line in text.splitlines():
        stripped = line.strip()
        if any(fnmatch.fnmatch(stripped, pat) for pat in patterns):
            continue
        if (
            strip_comments
            and stripped.startswith("<!--")
            and stripped.endswith("-->")
            and len(stripped) > 7
        ):
            continue
        kept.append(line)
    collapsed = re.sub(r"\n{3,}", "\n" * int(rules.get("collapse_blank_lines", 2)), "\n".join(kept))
    return collapsed.strip("\n") + "\n"


def apply_overlays(
    body: str, overlays: list[dict[str, Any]], locale: str, entry_path: str
) -> tuple[str, list[str]]:
    """Anchored find/replace. Zero or 2+ matches of the anchor = DRIFT fail."""
    applied: list[str] = []
    for rule in overlays or []:
        if rule.get("file") != f"{locale}/{entry_path}":
            continue
        find = rule["find"]
        count = body.count(find)
        if count != 1:
            raise SyncError(
                f"overlay DRIFT on {locale}/{entry_path}: anchor matched "
                f"{count} times (expected 1) — upstream changed, update the "
                f"rule. Reason on record: {rule.get('reason', 'n/a')}"
            )
        body = body.replace(find, rule["replace"])
        applied.append(rule.get("reason", find[:40]))
    return body, applied


def split_anchor(target: str) -> tuple[str, str]:
    """`page.md#sec` -> (`page.md`, `#sec`); pure anchors -> (``, `#sec`)."""
    if target.startswith("#"):
        return "", target
    path, sep, anchor = target.partition("#")
    return path, (sep + anchor)


def page_slug_for(project: str, locale_dirs: dict[str, str], resolved: str) -> str | None:
    """If `resolved` (repo-relative) is a docs locale page, its board slug."""
    for locale_dir in locale_dirs.values():
        prefix = locale_dir.rstrip("/") + "/"
        if resolved.startswith(prefix) and resolved.endswith(MD_EXT):
            return f"{project}/{resolved[len(prefix):][: -len(MD_EXT)]}"
    return None


def first_h1(body: str) -> str | None:
    for line in body.splitlines():
        match = HEADING1_RE.match(line.strip())
        if match:
            return match.group(1).strip()
    return None


def split_frontmatter(text: str, where: str) -> tuple[dict[str, str], str]:
    """Split a leading `---` block of `key: value` lines (viewer-compatible).

    Returns (fields, body). Curated translations are writer-authored, so a
    malformed frontmatter block is an authoring bug -> loud SyncError.
    """
    if not text.startswith("---\n"):
        return {}, text
    lines = text.splitlines()
    close = next(
        (i for i in range(1, len(lines)) if lines[i].strip() == "---"), None
    )
    if close is None:
        raise SyncError(f"{where}: frontmatter opened but never closed")
    fields: dict[str, str] = {}
    for line in lines[1:close]:
        stripped = line.strip()
        if not stripped:
            continue
        key, sep, value = stripped.partition(":")
        if not key.strip() or not sep or not value.strip():
            raise SyncError(f"{where}: malformed frontmatter line {line!r}")
        fields[key.strip()] = value.strip().strip("'\"")
    return fields, "\n".join(lines[close + 1 :])


class Rewriter:
    """Rewrites markdown links/images of one source file (contract §6.1/§6.4)."""

    def __init__(
        self,
        *,
        project: str,
        repo: Path,
        sha: str,
        web_base: str,
        locale_dirs: dict[str, str],
        source_dir: str,
        assets_out: Path,
        stats: dict[str, list[Any]],
    ) -> None:
        self.project = project
        self.repo = repo
        self.sha = sha
        self.web_base = web_base
        self.locale_dirs = locale_dirs
        self.source_dir = source_dir  # repo-relative dir of the source file
        self.assets_out = assets_out
        self.stats = stats

    def _resolve(self, target: str) -> str | None:
        """Repo-relative resolution; None when the link escapes the clone."""
        resolved = posixpath.normpath(posixpath.join(self.source_dir, target))
        if resolved.startswith(".."):
            self.stats["escapes"].append(target)
            return None
        return resolved

    def _github_url(self, resolved: str, anchor: str) -> str | None:
        """Pinned blob URL for repo files outside the docs locale pages."""
        if not self.web_base:
            return None
        if not (self.repo / resolved).is_file():
            self.stats["missing_targets"].append(resolved)
            return None
        return f"{self.web_base.format(sha=self.sha)}/{resolved}{anchor}"

    def rewrite(self, body: str) -> str:
        body = IMAGE_RE.sub(self._sub_image, body)
        return LINK_RE.sub(self._sub_link, body)

    def _sub_image(self, match: re.Match[str]) -> str:
        alt, target = match.group(1), match.group(2)
        if EXTERNAL_TARGET_RE.match(target) or target.startswith("/"):
            return match.group(0)
        path, anchor = split_anchor(target)
        if not path:
            return match.group(0)
        resolved = self._resolve(path)
        if resolved is None:
            return match.group(0)
        ext = Path(resolved).suffix.lower()
        source = self.repo / resolved
        if ext not in IMAGE_EXTS or not source.is_file():
            self.stats["missing_targets"].append(resolved)
            return match.group(0)
        dest = self.assets_out / self.project / resolved
        self.stats["asset_copies"].append((source, dest))
        self.stats["images"].append(resolved)
        return f"![{alt}](upstream/{self.project}/{resolved}{anchor})"

    def _sub_link(self, match: re.Match[str]) -> str:
        text, target = match.group(1), match.group(2)
        if EXTERNAL_TARGET_RE.match(target) or target.startswith("/"):
            return match.group(0)
        path, anchor = split_anchor(target)
        if not path:
            return match.group(0)  # pure in-page anchor
        resolved = self._resolve(path)
        if resolved is None:
            return match.group(0)  # cross-clone hop (e.g. mesh -> vesma): keep
        slug = page_slug_for(self.project, self.locale_dirs, resolved)
        if slug is not None:
            if slug not in self.stats["included_slugs"]:
                self.stats["dangling_slugs"].append(slug)
            return f"[{text}]({slug}{anchor})"
        url = self._github_url(resolved, anchor)
        if url is None:
            return match.group(0)  # missing upstream file: keep, warn
        self.stats["github_links"].append(resolved)
        return f"[{text}]({url})"


# --------------------------------------------------------------------------
# page assembly
# --------------------------------------------------------------------------

def resolve_title(entry: dict[str, Any], locale: str, body: str, fallback: str) -> str:
    title = entry.get("title")
    if isinstance(title, dict):
        title = title.get(locale)
    elif isinstance(title, str):
        pass
    else:
        title = None
    if not title:
        title = first_h1(body) or fallback
    return re.sub(r"\s+", " ", str(title)).strip()


def frontmatter_block(fields: list[tuple[str, str]]) -> str:
    lines = ["---"]
    lines.extend(f"{key}: {value}" for key, value in fields)
    lines.append("---")
    return "\n".join(lines)


def assemble_page(
    *,
    fields: list[tuple[str, str]],
    banner: str,
    note: str | None,
    body: str,
) -> str:
    parts = [frontmatter_block(fields), "", banner, ""]
    if note:
        parts.extend([f"> {note}", ""])
    parts.append(body.rstrip("\n"))
    return "\n".join(parts) + "\n"


# --------------------------------------------------------------------------
# contentClass gate (ME-011, ADR 0020 layer 1)
# --------------------------------------------------------------------------

def _verify_content_class_gate(
    sidecar_pages: dict[str, dict[str, Any]],
    provenance_files: dict[str, dict[str, Any]],
    content_out: Path,
) -> None:
    """The layer-1 integrity gate over the SYNC OUTPUT (fail-closed).

    Checks, in order:
    1. every ``provenance.json`` entry has a sidecar page (the sidecar
       covers the corpus — a diverged provenance is an untrusted channel);
    2. every sidecar page carries the uniform ``contentClass: "corpus"``
       stamp for EACH of its published locales;
    3. every CORPUS FILE on disk maps to a provenance entry — a planted
       orphan/manual file poisons the build (the post-build check the CI
       gate re-runs on a tampered tree).

    Deterministic: reads only the in-memory mappings plus the output tree;
    no wall-clock, stable order.
    """
    # 1+2. provenance entries ↔ sidecar pages, uniform stamp.
    for slug, locales in sorted(provenance_files.items()):
        page = sidecar_pages.get(slug)
        if page is None:
            raise SyncError(
                f"contentClass gate: provenance entry {slug!r} has no "
                "sidecar page — provenance/sidecar diverged"
            )
        stamped = page.get("contentClass") or {}
        missing = [
            loc for loc in sorted(locales) if stamped.get(loc) != "corpus"
        ]
        if missing:
            raise SyncError(
                f"contentClass gate: page {slug!r} is not stamped 'corpus' "
                f"for locales {missing} — the channel is untrusted"
            )
    for slug in sorted(sidecar_pages):
        if slug not in provenance_files:
            raise SyncError(
                f"contentClass gate: sidecar page {slug!r} has no "
                "provenance.json entry — orphan/manual file planting is "
                "forbidden (fail-closed)"
            )
    # 3. the on-disk corpus is exactly the provenance set (orphans die).
    if content_out.exists():
        for page_path in sorted(content_out.rglob("*.md")):
            if page_path.name in (PROVENANCE_NAME, SIDECAR_NAME):
                continue
            relative = page_path.relative_to(content_out)
            parts = relative.parts
            if len(parts) < 3:
                raise SyncError(
                    f"contentClass gate: corpus file {relative!r} is not "
                    "under <project>/<locale>/ — manual planting"
                )
            slug = f"{parts[0]}/{Path(*parts[2:])!s}".replace("\\\\", "/")
            for suffix in (".md",):
                slug = slug[: -len(suffix)] if slug.endswith(suffix) else slug
            if slug not in provenance_files:
                raise SyncError(
                    f"contentClass gate: corpus file "
                    f"{relative.as_posix()!r} has no provenance.json entry "
                    "— orphan/manual file planting is forbidden "
                    "(fail-closed)"
                )


# --------------------------------------------------------------------------
# sync
# --------------------------------------------------------------------------

def sync(
    config: dict[str, Any],
    content_out: Path = CONTENT_UPSTREAM,
    assets_out: Path = ASSETS_UPSTREAM,
    repo_root: Path = REPO_ROOT,
) -> dict[str, Any]:
    """Regenerate L2. Byte-stable on repeated runs with the same pins.

    `repo_root` anchors every repo-relative path: upstream clones
    (`projects.*.repo`) and curated translation sources
    (`projects.*.translations.*.source`). Tests pass a tmp root so the real
    viewer tree is never touched.
    """
    rules = normalize_rules(config)
    projects: dict[str, Any] = config["projects"]

    # --- resolve pins first (fail fast before touching L2) ----------------
    pins: dict[str, dict[str, str]] = {}
    for name, project in projects.items():
        repo = (repo_root / project["repo"]).resolve()
        if not (repo / ".git").exists():
            raise SyncError(f"{name}: clone not found at {repo}")
        assert_pristine(repo, name)
        sha = resolve_pin(repo, name, project["ref"])
        assert_head_at_pin(repo, name, project["ref"], sha)
        pins[name] = {
            "repo_path": str(repo),
            "sha": sha,
            "commit_date": commit_iso(repo, sha),
        }

    # --- phase A: compute every output in memory (fail-fast on drift) -----
    provenance_files: dict[str, dict[str, Any]] = {}
    pending_files: list[tuple[Path, str]] = []
    pending_assets: list[tuple[Path, Path]] = []
    sidecar_pages: dict[str, dict[str, Any]] = {}
    report: dict[str, Any] = {"projects": {}, "skipped": []}

    for name, project in projects.items():
        validate_selection(name, project)
        pin = pins[name]
        repo = Path(pin["repo_path"])
        sha = pin["sha"]
        commit_date = pin["commit_date"]
        locale_dirs: dict[str, str] = project["locale_dirs"]
        overlays: list[dict[str, Any]] = project.get("overlays") or []
        included_slugs = {
            f"{name}/{entry['path'][: -len(MD_EXT)]}" for entry in project["include"]
        }

        stats: dict[str, list[str]] = {
            "included_slugs": sorted(included_slugs),
            "asset_copies": [],
            "images": [],
            "dangling_slugs": [],
            "github_links": [],
            "escapes": [],
            "missing_targets": [],
            "overlays_applied": [],
        }
        per_locale: dict[str, dict[str, int]] = {}

        for locale, locale_dir in locale_dirs.items():
            written = 0
            bytes_total = 0
            for entry in project["include"]:
                entry_path = entry["path"]
                source = repo / locale_dir / entry_path
                if not source.is_file():
                    report["skipped"].append(
                        {
                            "project": name,
                            "locale": locale,
                            "path": entry_path,
                            "why": "source file missing in pinned clone",
                        }
                    )
                    continue
                raw = source.read_text(encoding="utf-8")
                body = strip_chrome(raw, rules)
                body = normalize_mermaid_labels(body)
                body, applied = apply_overlays(body, overlays, locale, entry_path)
                stats["overlays_applied"].extend(applied)
                rewriter = Rewriter(
                    project=name,
                    repo=repo,
                    sha=sha,
                    web_base=project.get("web_base", ""),
                    locale_dirs=locale_dirs,
                    source_dir=posixpath.dirname(posixpath.join(locale_dir, entry_path)),
                    assets_out=assets_out,
                    stats=stats,
                )
                body = rewriter.rewrite(body)

                slug = f"{name}/{entry_path[: -len(MD_EXT)]}"
                fallback_title = entry_path[: -len(MD_EXT)].replace("/", " · ").replace("-", " ")
                title = resolve_title(entry, locale, body, fallback_title)
                order = entry["order"]
                note = entry.get("note")
                if isinstance(note, dict):
                    note = note.get(locale)
                note = str(note).strip() if note else None

                page = assemble_page(
                    fields=[
                        ("title", title),
                        ("slug", slug),
                        ("category", str(entry["category"])),
                        ("order", str(int(order))),
                        ("last_verified", commit_date[:10]),
                    ],
                    banner=BANNER_TEMPLATE.format(project=name, sha=sha[:12]),
                    note=note,
                    body=body,
                )
                dest = content_out / name / locale / entry_path
                pending_files.append((dest, page))
                written += 1
                bytes_total += len(page.encode("utf-8"))

                provenance_files.setdefault(slug, {})[locale] = {
                    "repo": name,
                    "source_path": f"{locale_dir}/{entry_path}",
                    "sha": sha,
                    "commit_date": commit_date,
                    "synced_at": commit_date,
                    "locale": locale,
                    "kind": "upstream",
                }
                page_entry = sidecar_pages.setdefault(
                    slug,
                    {
                        "slug": slug,
                        "titles": {},
                        "category": str(entry["category"]),
                        "order": int(order),
                        "lastVerified": commit_date[:10],
                        "locales": [],
                        "provenance": {
                            "repo": name,
                            "source_path": f"{locale_dir}/{entry_path}",
                            "sha": sha,
                            "commit_date": commit_date,
                        },
                    },
                )
                page_entry["titles"][locale] = title
                page_entry["locales"] = sorted(page_entry["titles"])
                # ME-011 (ADR 0020 layer-1 gate): the corpus stamp is UNIFORM
                # on every sidecar page — the provenance kind of the FILE
                # lives in provenance.json (`kind`), the STAMP is the same
                # value for the whole corpus. Its absence (or a mismatch
                # against provenance.json) = an untrusted channel, fail-closed
                # in the CI gate (tests/test_sync_docs.py).
                page_entry.setdefault("contentClass", {})[locale] = "corpus"
            per_locale[locale] = {"files": written, "raw_bytes": bytes_total}

        # --- curated translations (W3 prep): our layer, re-sync-proof -------
        # Published through the SAME phase-A/phase-B path as upstream pages:
        # the slot is recomputed from the curated source every run, so the
        # project wipe can never lose it. Missing curated file = warning.
        translations_published: list[str] = []
        for locale, entries in (project.get("translations") or {}).items():
            if locale in locale_dirs:
                raise SyncError(
                    f"{name}: translation locale {locale!r} collides with an "
                    f"upstream mirror in locale_dirs — translations are for "
                    f"locales the upstream does not ship"
                )
            include_entries = {entry["path"]: entry for entry in project["include"]}
            for entry in entries:
                source_of = entry.get("source_of")
                if source_of not in include_entries:
                    raise SyncError(
                        f"{name}: translation source_of {source_of!r} is not "
                        f"an included page — fix sync-config.yaml"
                    )
                source_rel = entry.get("source")
                if not source_rel:
                    raise SyncError(
                        f"{name}: translation for {source_of!r} lacks `source`"
                    )
                curated = repo_root / source_rel
                if not curated.is_file():
                    report["skipped"].append(
                        {
                            "project": name,
                            "locale": locale,
                            "path": source_rel,
                            "why": "curated translation file missing",
                        }
                    )
                    continue
                meta, body = split_frontmatter(
                    curated.read_text(encoding="utf-8"), str(curated)
                )
                # Curated bodies go through the same L1 mermaid-label rule:
                # writers are human, the same literal-`\n` slip can land here.
                body = normalize_mermaid_labels(body)
                slug = f"{name}/{source_of[: -len(MD_EXT)]}"
                en_entry = include_entries[source_of]
                fallback = source_of[: -len(MD_EXT)].replace("-", " ")
                title = meta.get("title") or first_h1(body) or fallback
                page = assemble_page(
                    fields=[
                        ("title", re.sub(r"\s+", " ", title).strip()),
                        ("slug", slug),
                        ("category", str(en_entry["category"])),
                        ("order", str(int(en_entry["order"]))),
                        ("last_verified", commit_date[:10]),
                    ]
                    + [
                        (key, value)
                        for key, value in meta.items()
                        if key
                        not in {"title", "slug", "category", "order", "last_verified"}
                    ],
                    banner=CURATED_BANNER_TEMPLATE.format(
                        project=name, sha=sha[:12], source=source_rel
                    ),
                    note=None,
                    body=body,
                )
                slot = content_out / name / locale / source_of
                pending_files.append((slot, page))
                translations_published.append(f"{locale}/{source_of}")
                provenance_files.setdefault(slug, {})[locale] = {
                    "repo": name,
                    "source_path": source_rel,
                    "sha": sha,
                    "source_sha": sha,
                    "commit_date": commit_date,
                    "synced_at": commit_date,
                    "locale": locale,
                    "kind": "curated-translation",
                    **(
                        {"translator_note": str(entry["translator_note"])}
                        if entry.get("translator_note")
                        else {}
                    ),
                }
                page_entry = sidecar_pages.setdefault(
                    slug,
                    {
                        "slug": slug,
                        "titles": {},
                        "category": str(en_entry["category"]),
                        "order": int(en_entry["order"]),
                        "lastVerified": commit_date[:10],
                        "locales": [],
                        "provenance": {
                            "repo": name,
                            "source_path": f"{locale_dirs[next(iter(locale_dirs))]}/{source_of}",
                            "sha": sha,
                            "commit_date": commit_date,
                        },
                    },
                )
                page_entry["titles"][locale] = re.sub(r"\s+", " ", title).strip()
                page_entry["locales"] = sorted(page_entry["titles"])
                page_entry.setdefault("kinds", {})[locale] = "curated-translation"
                # ME-011: same uniform corpus stamp — translations are corpus
                # too (the channel, not the content, is what is being stamped).
                page_entry.setdefault("contentClass", {})[locale] = "corpus"

        pending_assets.extend(stats["asset_copies"])

        report["projects"][name] = {
            "sha": sha,
            "commit_date": commit_date,
            "locales": per_locale,
            "translations": sorted(translations_published),
            "images": sorted(stats["images"]),
            "dangling_slugs": sorted(set(stats["dangling_slugs"])),
            "github_links": sorted(set(stats["github_links"])),
            "escapes": sorted(set(stats["escapes"])),
            "missing_targets": sorted(set(stats["missing_targets"])),
            "overlays_applied": stats["overlays_applied"],
        }

    # --- phase B: wipe L2 and write everything (fail-fast happened above) --
    # Full wipe -> stale selections can never leak into the corpus (§6.6).
    if content_out.exists():
        for child in content_out.iterdir():
            if child.name in (PROVENANCE_NAME, SIDECAR_NAME):
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    content_out.mkdir(parents=True, exist_ok=True)
    if assets_out.exists():
        for child in assets_out.iterdir():
            if child.name not in projects:
                shutil.rmtree(child) if child.is_dir() else child.unlink()
    for name in projects:
        shutil.rmtree(assets_out / name, ignore_errors=True)
    assets_out.mkdir(parents=True, exist_ok=True)
    for dest, page in pending_files:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(page, encoding="utf-8")
    for source, dest in pending_assets:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, dest)

    # --- manifests ---------------------------------------------------------
    for page in sidecar_pages.values():
        page["locales"] = sorted(page["locales"])

    # --- ME-011 contentClass gate (ADR 0020, layer 1) ----------------------
    # Every CORPUS file must map to a provenance.json entry AND every
    # sidecar page must carry the uniform `contentClass` stamp. A planted
    # orphan/manual file has NO provenance entry -> the sync output is
    # poisoned -> the sync fails here (fail-closed, build-time).
    _verify_content_class_gate(
        sidecar_pages, provenance_files, content_out
    )

    now_pin_dates = {name: pin["commit_date"] for name, pin in pins.items()}
    provenance = {
        "version": 1,
        "generated_by": "scripts/sync_docs.py",
        # Deterministic "sync time": the pinned commits' dates. Wall-clock
        # would break the byte-stable re-sync gate; drift is visible via SHA.
        "synced_at": max(now_pin_dates.values()) if now_pin_dates else None,
        "projects": {
            name: {
                "repo": projects[name]["repo"],
                "ref": projects[name]["ref"],
                "sha": pins[name]["sha"],
                "commit_date": pins[name]["commit_date"],
            }
            for name in projects
        },
        "files": dict(sorted(provenance_files.items())),
    }
    sidecar = {
        "version": 1,
        "generated_by": "scripts/sync_docs.py",
        "source_shas": {name: pins[name]["sha"] for name in projects},
        # Field shape mirrors viewer DocPage (manifest.ts): slug, titles,
        # category, order, lastVerified, locales + per-page provenance.
        "pages": [sidecar_pages[slug] for slug in sorted(sidecar_pages)],
    }
    (content_out / PROVENANCE_NAME).write_text(
        json.dumps(provenance, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (content_out / SIDECAR_NAME).write_text(
        json.dumps(sidecar, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    report["pins"] = {name: pins[name]["sha"] for name in pins}
    report["pages"] = len(sidecar_pages)
    report["skipped"].sort(key=lambda item: (item["project"], item["locale"], item["path"]))
    return report


def print_sync_report(report: dict[str, Any]) -> None:
    for name, info in report["projects"].items():
        locales = ", ".join(
            f"{loc}: {stat['files']} files / {stat['raw_bytes']} B"
            for loc, stat in info["locales"].items()
        )
        print(f"[{name}] pinned {info['sha'][:12]} ({info['commit_date'][:10]}) — {locales}")
        if info["translations"]:
            print(f"  curated translations published: {len(info['translations'])}")
            for slug in info["translations"]:
                print(f"    - {slug}")
        if info["images"]:
            print(f"  vendored images ({len(info['images'])}):")
            for image in info["images"]:
                print(f"    - {image}")
        if info["dangling_slugs"]:
            print(
                f"  links to pages outside the selection "
                f"({len(info['dangling_slugs'])} unique slugs — W2 may include or overlay):"
            )
            for slug in info["dangling_slugs"]:
                print(f"    - {slug}")
        if info["github_links"]:
            print(f"  links rewritten to pinned GitHub URLs: {len(info['github_links'])}")
        if info["escapes"]:
            print(f"  links escaping the clone (left as-is): {info['escapes']}")
        if info["missing_targets"]:
            print(f"  link targets missing upstream (left as-is): {info['missing_targets']}")
        if info["overlays_applied"]:
            print(f"  overlays applied: {len(info['overlays_applied'])}")
    for skip in report["skipped"]:
        print(f"[skip] {skip['project']}/{skip['locale']}/{skip['path']}: {skip['why']}")
    print(
        f"total: {report['pages']} pages, "
        f"provenance + sidecar written to {CONTENT_UPSTREAM}"
    )


# --------------------------------------------------------------------------
# drift check
# --------------------------------------------------------------------------

def check_drift(config: dict[str, Any]) -> dict[str, Any]:
    """Report-only comparison of pinned refs vs clone HEADs (contract §7)."""
    report: dict[str, Any] = {"projects": {}}
    for name, project in config["projects"].items():
        repo = (REPO_ROOT / project["repo"]).resolve()
        pinned = resolve_pin(repo, name, project["ref"])
        head = resolve_sha(repo, "HEAD")
        dirty = tracked_dirty(repo)
        new_docs: list[str] = []
        status = "OK"
        if head != pinned:
            status = "DRIFT"
            log = run_git(
                repo, "log", "--oneline", "--", *project["locale_dirs"].values(),
                f"{pinned}..{head}",
            )
            new_docs = log.splitlines()[:10]
        report["projects"][name] = {
            "pinned": pinned,
            "head": head,
            "drift": head != pinned,
            "dirty": dirty,
            "new_doc_commits": new_docs,
        }
        print(f"[{name}] pin {pinned[:12]} vs HEAD {head[:12]}: {status}")
        for line in new_docs:
            print(f"    new: {line}")
        if dirty:
            print(f"    WARNING: clone has {len(dirty)} tracked modifications")
    return report


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "command", nargs="?", choices=("sync", "check-drift"), default=None,
        help="sync (default) regenerates L2; check-drift compares pins with clones",
    )
    parser.add_argument(
        "--check-drift", action="store_true",
        help="flag alias of the check-drift subcommand",
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args(argv)

    config = load_config(args.config)
    if args.check_drift and args.command == "sync":
        parser.error("--check-drift conflicts with the sync command")
    if args.check_drift or args.command == "check-drift":
        check_drift(config)
        return 0
    try:
        report = sync(config)
    except SyncError as error:
        print(f"sync_docs: {error}", file=sys.stderr)
        return 1
    print_sync_report(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
